#
# DO NOT EDIT THIS FILE!!!  Edit .\sources. if you want to add a new source
# file to this component.  This file merely indirects to the real make file
# that is shared by all the driver components of the Windows NT DDK
#

# 2000
!INCLUDE $(NTMAKEENV)\makefile.def

# 98
#!INCLUDE "C:\Progra~1\NTDDK\inc\win_me\makefile.def 