// Inline definitions of stuff from HTMLPages

// These save users having to update HTMLPages every time something changes

// Doing it as functions instead of static text allows edit and continue debugging

#include "common_web_components.h"
#include "compatbits.h"

char * WebMailMsgtxt()
{
	static const char Msg[] =

		"<!-- Version 5 11/11/2019 -->"
		"<!DOCTYPE html> "
		"<html lang=\"en\"> "
		"<head> "
		"<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\"/>"
		"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>"
		"<style type=\"text/css\">"
		COMMON_CSS_ROOT
		COMMON_REDUCED_MOTION_CSS
		"*{box-sizing:border-box;}"
		"body{margin:0;padding:12px;font-family:" COMMON_FONT_MONO ";background:var(--bg);color:var(--text);min-height:100dvh;}"
		".wm-shell{max-width:980px;margin:0 auto;display:flex;flex-direction:column;min-height:calc(100dvh - 24px);}"
		".wm-title{text-align:center;margin:0 0 12px 0;font-family:" COMMON_FONT_TITLE ";font-size:clamp(1.25rem,3vw,1.75rem);}"
		COMMON_WEBMAIL_MENU_BTN_BASE_CSS
		"#main{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:12px;flex:1 1 auto;min-height:0;overflow:auto;display:flex;flex-direction:column;}"
		"textarea#txt{display:block;width:100%%;height:100%%;min-height:320px;border:0;margin:0;padding:8px;font-family: " COMMON_FONT_MONO ";font-size:clamp(0.9375rem,0.9rem + 0.2vw,1rem);line-height:1.45;overflow:auto;resize:vertical;background:var(--surface);color:var(--text);flex:1 1 auto;}"
		"div#txt{display:block;width:100%%;min-height:320px;border:0;margin:0;padding:8px;font-family: " COMMON_FONT_MONO ";font-size:clamp(0.9375rem,0.9rem + 0.2vw,1rem);line-height:1.45;white-space:pre-wrap;overflow-wrap:anywhere;flex:1 1 auto;}"
		"@media (max-width:768px){body{padding:8px;}.wm-shell{min-height:calc(100dvh - 16px);}.menu-header{display:block;}.wm-menu{display:none;flex-direction:column;align-items:stretch;margin-top:0;}.wm-menu.menu-open{display:flex;}.wm-menu .wm-btn{width:100%%;text-align:center;}#main{padding:10px;}textarea#txt{min-height:240px;font-size:clamp(0.9375rem,0.9rem + 0.2vw,1rem);}div#txt{min-height:240px;font-size:clamp(0.9375rem,0.9rem + 0.2vw,1rem);}}"
		"</style>\r\n"
		"<script>"
		"function Reply(Num, Key)"
		"{"
		"var param = \"toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,resizable=yes,titlebar=yes,toobar=yes\";"
		"window.open(\"/WebMail/Reply/\" + Num + \"?\" + Key,\"_self\",param);"
		"}\r\n"
		COMMON_MENU_JAVASCRIPT
		"</script>\r\n"
		"<title>WebMail</title> "
		"</head>\r\n"
		"<body>"
		"<div class=\"wm-shell\">"
		"<h2 class=\"wm-title\"> %s Webmail - User %s - Message %d</h2>"
		"<div class=\"menu-header\"><button id=\"menuToggle\" class=\"menu-toggle\" type=\"button\" aria-expanded='false' aria-controls='mainMenu' onclick=\"toggleMenu(event)\">Menu</button></div>"
		"<nav id=\"mainMenu\" class=\"wm-menu\">"
		"<a class=\"wm-btn\" href=\"#\" onclick=\"Reply('%d' ,'%s'); return false;\">Reply</a>"
		"<a class=\"wm-btn\" href=/WebMail/WMDel/%d?%s>Kill Message</a>"
		"%s"
		"<a class=\"wm-btn\" href=/WebMail/WMPrev?%s>Previous</a>"
		"<a class=\"wm-btn\" href=/WebMail/WMNext?%s>Next</a>"
		"<a class=\"wm-btn\" href=/WebMail/WMSame?%s>Back to List</a>"
		"</nav>"
		"<div id=\"main\">"
		"<%s id=\"txt\">%s</%s>"
		"</div>"
		"</div>"
		"</body></html>";

	return _strdup(Msg);
}

char * FwdPagetxt()
{
	static const char Msg[] =

		"<!-- Version 5 3/8/2026 Responsive -->"
		"<!DOCTYPE html>"
		"<html lang=\"en\"><head>"
		"<meta charset=\"UTF-8\">"
		"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
		COMMON_BPQ_CSS_LINK
		"<style type=\"text/css\"> "
		"body { font-family: " COMMON_FONT_MONO "; background: var(--bg); color: var(--text); margin: 0; padding: 20px; }"
		"h3 { text-align: center; margin: 0 0 20px; font-family: " COMMON_FONT_TITLE "; font-size: clamp(1.25rem,3vw,1.75rem); }"
		COMMON_WEBMAIL_TITLE_STRONG_CSS
		COMMON_SECTION_TITLE_CSS
		".fwd-container { max-width: 980px; margin: 0 auto; }"
		".fwd-layout { display: flex; gap: 20px; flex-wrap: wrap; align-items: start; }"
		".fwd-sidebar { flex: 0 0 280px; min-width: 0; display: flex; flex-direction: column; max-height: calc(100vh - 180px); }"
		".fwd-common { background: var(--surface); padding: 15px; border: 1px solid var(--border); border-radius: 8px; margin-bottom: 15px; box-shadow: var(--shadow-card); flex-shrink: 0; }"
		".fwd-list { background: var(--surface); padding: 15px; border: 1px solid var(--border); border-radius: 8px; overflow: hidden; box-shadow: var(--shadow-card); flex: 1 1 auto; display: flex; flex-direction: column; min-height: 0; }"
		".fwd-list a.active { background: var(--surface-soft); }"
		COMMON_ADMIN_LIST_TOGGLE_CSS_TEMPLATE(".fwd-list-toggle")
		".fwd-list-toggle { font-size: clamp(0.875rem,1.5vw,1rem); }"
		".fwd-list-toggle:hover { background: var(--surface-soft); }"
		COMMON_ADMIN_LIST_BODY_CSS_TEMPLATE(".fwd-list-body")
		".fwd-list table { width: 100%%; border-collapse: collapse; }"
		".fwd-list table tr:nth-child(even) { background: var(--table-stripe); }"
		".fwd-list td { border-bottom: 1px solid var(--border-light); padding: 0; }"
		".fwd-list a { color: var(--text); text-decoration: none; display: block; padding: 8px 10px; border-radius: 0; font-family: " COMMON_FONT_MONO "; font-weight: 600; text-transform: uppercase; }"
		".fwd-list a:hover { background: var(--surface-soft); text-decoration: none; }"
		".fwd-list a:focus-visible { outline: 3px solid var(--focus-ring); outline-offset: -3px; }"
		".fwd-main { flex: 1 1 500px; min-width: 0; background: var(--surface); padding: 20px; border: 1px solid var(--border); border-radius: 8px; box-shadow: var(--shadow-card); min-height: 400px; }"
		".fwd-form-row { display: flex; flex-wrap: wrap; margin: 10px 0; gap: 10px; align-items: center; }"
		".fwd-form-row label { flex: 1 1 150px; font-weight: 600; font-size: clamp(0.8125rem,1.5vw,0.9375rem); }"
		".fwd-form-row input[type=text], .fwd-form-row input[type=number] { flex: 2 1 100px; padding: clamp(10px,1vw,14px) clamp(12px,1.5vw,16px); line-height: 1.5; box-sizing: border-box; border: 1px solid var(--border); border-radius: 6px; background: var(--surface-soft); color: var(--text); max-width: 200px; min-height: 44px; font-size: clamp(0.875rem,2vw,1rem); }"
		".fwd-form-row input[type=checkbox] { margin: 0 5px; width: 18px; height: 18px; }"
		".fwd-form-row textarea { width: 100%%; padding: clamp(10px,1vw,14px) clamp(12px,1.5vw,16px); line-height: 1.6; box-sizing: border-box; border: 1px solid var(--border); border-radius: 6px; background: var(--surface-soft); color: var(--text); font-family: " COMMON_FONT_MONO "; font-size: clamp(0.875rem,2vw,1rem); min-height: 120px; resize: vertical; }"
		".fwd-form-row input[type=text]:focus-visible, .fwd-form-row input[type=number]:focus-visible, .fwd-form-row textarea:focus-visible { outline: 3px solid var(--focus-ring); outline-offset: 2px; }"
		".fwd-common form { text-align: left; }"
		".fwd-common input[type=submit] { background: var(--surface); color: var(--text); padding: clamp(10px,1.5vw,16px) clamp(16px,2vw,28px); border: 1px solid var(--border); border-radius: 6px; cursor: pointer; margin-top: 10px; width: 100%%; min-height: 44px; font-size: clamp(0.875rem,1.5vw,1rem); }"
		".fwd-common input[type=submit]:hover { background: var(--surface-hover); }"
		".fwd-common input[type=submit]:active { background: var(--primary-dark); color: var(--on-primary); }"
		".fwd-common input[type=submit]:focus-visible { outline: 3px solid var(--focus-ring); outline-offset: 2px; }"
		"@media (max-width:768px) {"
		"body { padding: 10px; }"
		".fwd-layout { flex-direction: column; align-items: stretch; }"
		".fwd-sidebar { display: flex; flex-direction: column; flex: none; width: 100%%; max-height: none; }"
		COMMON_ADMIN_COLLAPSIBLE_LIST_MOBILE_CSS_TEMPLATE(".fwd-list", ".fwd-list-body", ".fwd-list-toggle", ".fwd-list.collapsed .fwd-list-body")
		".fwd-common { order: 2; }"
		".fwd-main { padding: 15px; }"
		".fwd-form-row { flex-direction: column; align-items: flex-start; }"
		".fwd-form-row label, .fwd-form-row input[type=text], .fwd-form-row input[type=number] { flex: none; width: 100%%; max-width: none; }"
		".fwd-form-row input[type=text], .fwd-form-row input[type=number], .fwd-form-row textarea, .fwd-common input[type=submit], .fwd-list-toggle { min-height: 48px; }"
		"}"
		"</style>"
		"<title>Edit Forwarding</title>"
		"<script type=\"text/javascript\"> "
		"var Details;"
		"var Sidebar;"
		"var CurrentFwd = \"\";"
		"var FwdListCollapsed = false;"
		"var Key = \"%s\"\r\n"
		"</script>"
		COMMON_BPQ_JS_SCRIPT
		"<script>"
		"function isMobile(){return window.matchMedia('(max-width: 768px)').matches;}"
		"function applyFwdListState(){var listWrapper=document.querySelector('#sidebar .fwd-list');if(!listWrapper)return;if(isMobile()&&FwdListCollapsed){listWrapper.classList.add('collapsed');}else{listWrapper.classList.remove('collapsed');}}"
		"function toggleFwdList(){if(!isMobile())return;FwdListCollapsed=!FwdListCollapsed;applyFwdListState();}"
		"function buildFwdList(lines){var i=0;var strInfo='<div class=\"fwd-list\"><button type=button class=\"fwd-list-toggle\" onclick=\"toggleFwdList()\">Forwarding BBS</button><div class=\"fwd-list-body\"><table>';while(i < lines.length - 1){var active=(lines[i]===CurrentFwd)?' class=\"active\"':'';var clink='<a'+active+' href=\\'javascript:GetDetails(\\\"'+lines[i]+'\\\",false)\\'>'+lines[i]+'</a>';strInfo += '<tr><td>' + clink + '</td></tr>';i=i+1;}return strInfo + '</table></div></div>';}"
		"window.addEventListener('resize', function(){ if (!isMobile()) FwdListCollapsed = false; applyFwdListState(); });"

		"function initialize()"
		"{"
		"	Details = document.getElementById('main'); "
		"	if (Details) { Details.innerHTML = 'waiting for data...'; GetData(''); }"
		"}\r\n"

		"function save(form)"
		"{"
		"	var msg;"
		"	var fn = \"FWDSave?\" + Key;"

		"	msg = "
		"	form.TO.value + \"|\" +"
		"	form.AT.value + \"|\" +"
		"	form.Times.value + \"|\" +"
		"	form.FWD.value + \"|\" +"
		"	form.HRB.value + \"|\" +"
		"	form.HRP.value + \"|\" +"
		"	form.BBSHA.value + \"|\" +"
		"	form.EnF.checked + \"|\" +"
		"	form.Interval.value + \"|\" +"
		"	form.EnR.checked + \"|\" + "
		"	form.RInterval.value + \"|\" +"
		"	form.NoWait.checked + \"|\" +"
		"	form.Blocked.checked + \"|\"  +"
		"	form.FBBBlock.value + \"|\"  +"
		"	form.Personal.checked + \"|\" +"
		"	form.Bin.checked + \"|\" +"
		"	form.B1.checked + \"|\" +"
		"	form.B2.checked + \"|\" +"
		"	form.CTRLZ.checked + \"|\" +"
		"	form.ConTimeOut.value + \"|\";"
		"	post(fn, msg);"
		"}\r\n"

		"function startf(form)"
		"{"
		"var fn = \"FWDSave?\" + Key;"
		"	post(fn, \"StartForward\", \"\");"
		"}\r\n"

		"function copyf(form)"
		"{"
		"	var msg;"
		"	var fn = \"FWDSave?\" + Key;"

		"	msg = \"CopyForward|\" + form.CopyCall.value;"

		"	post(fn, msg);"
		"}\r\n"

		"function post(url, data)"
		"{"
		"	if (window.XMLHttpRequest){request=new XMLHttpRequest();}else{request=new ActiveXObject(\"Microsoft.XMLHTTP\");}\r\n"
		"	request.onreadystatechange = function()\r\n"
		"	{if (request.readyState == 4){Details.innerHTML = request.responseText;}}\r\n"
		"	request.open(\"POST\", url, true);request.send(data);\r\n"
		"}\r\n"

		"function GetDetails(call, autoSelect)"
		"{"
		"	CurrentFwd = call;"
		"	if (!autoSelect && isMobile()) { FwdListCollapsed = true; applyFwdListState(); }"
		"	var fn = \"FwdDetails?\" + Key;"
		"	post(fn, call);"
		"}\r\n"
		"function GetData()"
		"{"
		"	if (window.XMLHttpRequest){request=new XMLHttpRequest();}else{request=new ActiveXObject(\"Microsoft.XMLHTTP\");}"

		"	request.onreadystatechange = function()"
		"	{"
		"		if (request.readyState == 4)"
		"		{"
		"			var text = request.responseText;"
		"			var lines = text.split(\"|\");"
		"			var infoArea = document.getElementById(\"sidebar\");"
		"			infoArea.innerHTML = buildFwdList(lines);"
		"			applyFwdListState();"
		"			GetDetails(lines[0], true);\r\n"
		"		}\r\n"
		"	}\r\n"
		"	request.open(\"POST\",\"FwdList.txt?%s\",true);\r\n"										   
		"	request.send();\r\n"
		"}\r\n"

		"  </script>\r\n"
		"</head><body onload=initialize()>"
		"<div class=\"fwd-container\">"
		"<h2 class=\"wm-title\">BPQ32 BBS %s</h2>"
		COMMON_MAIL_MENU
		"<div class=\"section-title\">Forwarding Management</div>"
		"<div class=\"fwd-layout\">"
		"<div class=\"fwd-sidebar\">"
		"<div class=\"fwd-common\">"
		"<form method=post action=/Mail/FwdCommon?%s>"
		"<div class=\"fwd-form-row\"><label>Max size to Send</label><input value=%d size=3 name=MaxTX type=number></div>"
		"<div class=\"fwd-form-row\"><label>Max Size to Receive</label><input value=%d size=3 name=MaxRX type=number></div>"
		"<div class=\"fwd-form-row\"><label>Max age for Bulls</label><input value=%d size=3 name=MaxAge type=number></div>"
		"<div class=\"fwd-form-row\"><label>Warn if no route for P or T</label><input %sname=WarnNoRoute type=checkbox /></div>"
		"<div class=\"fwd-form-row\"><label>Use Local Time</label><input %sname=LocalTime type=checkbox /></div>"
		"<div class=\"fwd-form-row\"><label>Send P Msgs to multiple BBS</label><input %sname=SendPtoMultiple type=checkbox /></div>"
		"<div class=\"fwd-form-row\"><label>Use 4 Char Continent Codes</label><input %sname=FourCharCont type=checkbox /></div>"
		"<div class=\"fwd-form-row\"><label>Aliases</label></div>"
		"<div class=\"fwd-form-row\"><textarea rows=8 name=Aliases>%s</textarea></div>"
		"<input name=Submit value=Update type=submit class='btn'></form>"
		"</div>"
		"<div id=\"sidebar\"> </div>"
		"</div>"
		"<div class=\"fwd-main\" id=\"main\"> </div>"
		"</div>"
		"</div>"
		"</body></html>";

	return _strdup(Msg);
}

char * FwdDetailtxt()
{
	static const char Msg[] =

		"<!-- Version 4 3/8/2026 Responsive -->\r\n"
		"<div class=\"fwd-detail-form\"><h3>Forwarding Config for %s - %d Messages Queued</h3><form method=post action=/Mail/FWD?%s>\r\n"
		"<div class=\"fwd-textarea-grid\">\r\n"
		"<div><label>TO</label><textarea name=TO>%s</textarea></div>\r\n"
		"<div><label>AT</label><textarea name=AT>%s</textarea></div>\r\n"
		"<div><label>TIMES</label><textarea name=Times>%s</textarea></div>\r\n"
		"<div class=\"fwd-textarea-wide\"><label>Connect Script</label><textarea name=FWD>%s</textarea></div>\r\n"
		"</div>\r\n"
		"<div class=\"fwd-textarea-grid\">\r\n"
		"<div class=\"fwd-textarea-wide\"><label>Hierarchical Routes (Flood Bulls)</label><textarea name=HRB>%s</textarea></div>\r\n"
		"<div class=\"fwd-textarea-wide\"><label>HR (Personals and Directed Bulls)</label><textarea name=HRP>%s</textarea></div>\r\n"
		"</div>\r\n"
		"<div class=\"fwd-detail-row\"><label>BBS HA</label><input class=fwd-bbsha value=\"%s\" name=BBSHA></div>\r\n"
		"<div class=\"fwd-detail-row\"><label>Enable Forwarding</label><input %sname=EnF type=checkbox><label class=fwd-secondary-label>Interval</label><input value=%d size=3 name=Interval type=number><span>(Secs)</span></div>\r\n"
		"<div class=\"fwd-detail-row\"><label>Request Reverse</label><input %sname=EnR type=checkbox><label class=fwd-secondary-label>Interval</label><input value=%d size=3 name=RInterval type=number><span>(Secs)</span></div>\r\n"
		"<div class=\"fwd-detail-row\"><label>Send new messages without waiting for poll timer</label><input %sname=NoWait type=checkbox></div>\r\n"
		"<div class=\"fwd-detail-row\"><label>FBB Blocked</label><input %sname=Blocked type=checkbox><label class=fwd-secondary-label>Max Block</label><input value=%d size=3 name=FBBBlock type=number></div>\r\n"
		"<div class=\"fwd-detail-row\"><label>Send Personal Mail Only</label><input %sname=Personal type=checkbox></div>\r\n"
		"<div class=\"fwd-detail-row\"><label>Allow Binary</label><input %sname=Bin type=checkbox><label class=fwd-secondary-label>Use B1 Protocol</label><input %sname=B1 type=checkbox><label class=fwd-secondary-label>Use B2 Protocol</label><input %sname=B2 type=checkbox></div>\r\n"
		"<div class=\"fwd-detail-row\"><label>Send ctrl/Z instead of /ex in text mode forwarding</label><input %sname=CTRLZ type=checkbox></div>\r\n"
		"<div class=\"fwd-detail-row\"><label>Incoming Connect Timeout</label><input value=%d size=3 name=ConTimeOut type=number><span>(Secs)</span></div>\r\n"
		"<div class=\"fwd-buttons\">\r\n"
		"<input onclick=copyf(this.form) value=\"Copy from BBS\" type=button class='btn'>\r\n"
		"<input class=fwd-copy-call value=\"\" size=3 name=CopyCall placeholder=\"Call\"> \r\n"
		"<input onclick=save(this.form) value=Update type=button class='btn'>\r\n"
		"<input onclick=startf(this.form) value=\"Start Forwarding\" type=button class='btn'>\r\n"
		"</div></form></div>\r\n";


	return _strdup(Msg);
}

char * webscriptjs()
{
	static const char Msg[] =
		"<!-- Version 2 17/10/2018 -->\r\n"
		"var Main\r\n"
		"\r\n"
		"function initialize(mainoffset)\r\n"
		"{\r\n"
		"	Main = document.getElementById(\"main\");\r\n"
		"\tif (!Main) return;\r\n"
		"\tif (window.matchMedia && window.matchMedia(\"(max-width: 768px)\").matches)\r\n"
		"\t{\r\n"
		"\t\tMain.style.left = \"0px\";\r\n"
		"\t\tMain.style.width = \"100%\";\r\n"
		"\t\tMain.style.height = \"auto\";\r\n"
		"\t\tMain.style.minHeight = \"0px\";\r\n"
		"\t\treturn;\r\n"
		"\t}\r\n"
		"\tif (mainoffset === undefined || mainoffset === null) mainoffset = 120;\r\n"
		"\tvar y = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;\r\n"
		"\tvar minheight = y - mainoffset;\r\n"
		"\tif (minheight < 240) minheight = 240;\r\n"
		"\tMain.style.left = \"0px\";\r\n"
		"\tMain.style.width = \"100%\";\r\n"
		"\tMain.style.height = \"auto\";\r\n"
		"\tMain.style.minHeight = minheight + \"px\";\r\n"
		"}\r\n"
		"function newmsg(Key)\r\n"
		"{\r\n"
		"var param = \"toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,resizable=yes,titlebar=yes,toobar=yes\";\r\n"
		"window.open(\"/WebMail/NewMsg?\" + Key,\"_self\",param);\r\n"
		"}\r\n"
		"function Reply(Num, Key)\r\n"
		"{\r\n"
		"var param = \"toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,resizable=yes,titlebar=yes,toobar=yes\";\r\n"
		"window.open(\"/WebMail/Reply/\" + Num + \"?\" + Key,\"_self\",param);\r\n"
		"}\r\n";

	return _strdup(Msg);
}





char * WebMailPagetxt()
{
	static const char Msg[] =
		"<!-- Version 6 8/11/2018 -->\r\n"
		"<!DOCTYPE html> \r\n"
		"<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\"> \r\n"
		"<head> \r\n"
		"<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\"/> \r\n"
		"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>"
		"<meta http-equiv=refresh content=300>"
		"<style type=\"text/css\">\r\n"
		COMMON_CSS_ROOT
		COMMON_REDUCED_MOTION_CSS
		COMMON_THEME_SELECTOR_CSS
		"body{margin:0;padding:max(12px,env(safe-area-inset-left));font-family:" COMMON_FONT_MONO ";background:var(--bg);color:var(--text);-webkit-font-smoothing:antialiased;}"
		"@supports(padding:max(0px)){body{padding:clamp(10px,3vw,12px);padding-left:max(clamp(10px,3vw,12px),env(safe-area-inset-left));padding-right:max(clamp(10px,3vw,12px),env(safe-area-inset-right));}}"
		".wm-shell{max-width:980px;margin:0 auto;}"
		".wm-title{text-align:center;margin:0 0 12px 0;font-family:" COMMON_FONT_TITLE ";font-size:clamp(1.25rem,3vw,1.75rem);font-weight:500;}"
		COMMON_WEBMAIL_MENU_LINK_TOUCH_BASE_CSS
		"#main{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:10px;min-height:calc(100dvh - 240px);overflow:auto;}"
		".msg-table{width:100%%;border-collapse:collapse;font-size:clamp(0.9375rem,0.9rem + 0.2vw,1rem);}"
		".msg-table thead{background:var(--table-header);border-bottom:2px solid var(--border);}"
		".msg-table th{padding:10px 6px;text-align:left;font-weight:600;white-space:nowrap;touch-action:manipulation;}"
		".msg-table td{padding:8px 6px;border-bottom:1px solid var(--border-light);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}"
		".msg-table tr.msg-row{cursor:pointer;}"
		".msg-table tr:hover{background:var(--surface-soft);}"
		".msg-table a{color:var(--link);text-decoration:none;}"
		".msg-table a:hover{text-decoration:underline;}"
		".msg-num{font-family: " COMMON_FONT_MONO ";}"
		".msg-date{font-family: " COMMON_FONT_MONO ";}"
		".msg-type{font-family: " COMMON_FONT_MONO ";min-width:24px;}"
		".msg-len{font-family: " COMMON_FONT_MONO ";min-width:50px;}"
		".msg-to,.msg-via,.msg-from{max-width:80px;}"
		".msg-subject{max-width:380px;}"
		"@media(min-width:1200px){.msg-subject{max-width:420px;}}"
		"@media(max-width:768px){"
		"body{padding:clamp(6px,2vw,10px);}.menu-header{display:block;}.wm-menu{display:none;flex-direction:column;align-items:stretch;margin-top:0;}.wm-menu.menu-open{display:flex;}.wm-menu a{width:100%%;text-align:center;min-height:48px;}#main{padding:8px;min-height:calc(100dvh - 280px);}"
		".msg-table{font-size:clamp(0.9375rem,0.9rem + 0.2vw,1rem);}"
		".msg-table th,.msg-table td{padding:6px 4px;}"
		".msg-date{font-size:clamp(0.9375rem,0.9rem + 0.2vw,1rem);}"
		".msg-to,.msg-via,.msg-from{max-width:60px;}"
		".msg-subject{max-width:180px;}"
		"}"
		"@media(max-width:520px){"
		".msg-len,.msg-via{display:none;}"
		".msg-to,.msg-from{max-width:50px;}"
		".msg-subject{max-width:120px;}"
		"}"
		"@media(max-width:380px){"
		".msg-date,.msg-from{display:none;}"
		".msg-len,.msg-via,.msg-type{display:none;}"
		".msg-to{max-width:45px;}"
		".msg-subject{max-width:100px;font-size:clamp(0.9375rem,0.9rem + 0.2vw,1rem);}"
		"}"
		"</style>\r\n"
		"<script src=\"/WebMail/webscript.js\"></script>\r\n"
		"<script>" COMMON_THEME_COOKIE_INIT_JAVASCRIPT COMMON_THEME_SELECTOR_INIT_JAVASCRIPT "function toggleMenu(event){if(event)event.preventDefault();var menu=document.getElementById('mainMenu');var toggle=document.getElementById('menuToggle');if(!menu||!toggle)return;if(menu.classList.contains('menu-open')){menu.classList.remove('menu-open');toggle.textContent='Menu';toggle.setAttribute('aria-expanded','false');}else{menu.classList.add('menu-open');toggle.textContent='Close';toggle.setAttribute('aria-expanded','true');}}function closeMenuOnMobile(){var menu=document.getElementById('mainMenu');var toggle=document.getElementById('menuToggle');if(!menu||!toggle)return;if(window.matchMedia('(max-width: 768px)').matches){menu.classList.remove('menu-open');toggle.textContent='Menu';toggle.setAttribute('aria-expanded','false');}}window.addEventListener('click',function(event){var menu=document.getElementById('mainMenu');var toggle=document.getElementById('menuToggle');var header=document.querySelector('.menu-header');if(menu&&toggle&&window.matchMedia('(max-width: 768px)').matches){var inMenu=menu.contains(event.target);var inHeader=header&&header.contains(event.target);if(!inMenu&&!inHeader){menu.classList.remove('menu-open');toggle.textContent='Menu';toggle.setAttribute('aria-expanded','false');}}});window.addEventListener('keydown',function(event){if(event.key==='Escape'){var menu=document.getElementById('mainMenu');if(menu&&menu.classList.contains('menu-open')){menu.classList.remove('menu-open');document.getElementById('menuToggle').textContent='Menu';document.getElementById('menuToggle').setAttribute('aria-expanded','false');}}});window.addEventListener('DOMContentLoaded',function(){var menu=document.getElementById('mainMenu');if(!menu)return;menu.addEventListener('click',function(event){var target=event.target;if(target&&target.tagName==='A')closeMenuOnMobile();});});</script>"
		"<title>WebMail</title> \r\n"
		"\r\n"
		"</head>\r\n"
		"<body onload=\"initialize(120)\" onresize=\"initialize(120)\">\r\n"
		COMMON_THEME_SELECTOR_HTML
		"<div class=\"wm-shell\">"
		"<h2 class=\"wm-title\"> %s Webmail - User %s - Messages</h2>\r\n"
		"<div class=\"menu-header\"><button id=\"menuToggle\" class=\"menu-toggle\" type=\"button\" aria-expanded=\"false\" aria-controls=\"mainMenu\" onclick=\"toggleMenu(event)\">Menu</button></div>"
		"<nav id=\"mainMenu\" class=\"wm-menu\">"
		"<a href=/WebMail/WMB?%s>Bulls</a>\r\n"
		"<a href=/WebMail/WMP?%s>Personal</a>\r\n"
		"<a href=/WebMail/WMT?%s>NTS</a>\r\n"
		"<a href=/WebMail/WMALL?%s>All Types</a>\r\n"
		"<a href=/WebMail/WMMine?%s>Mine</a>\r\n"
		"<a href=/WebMail/WMfromMe?%s>My Sent</a>\r\n"
		"<a href=/WebMail/WMtoMe?%s>My Rxed</a>\r\n"
		"<a href=/WebMail/WMAuto?%s>Auto Refresh</a>\r\n"
		"<a href=\"#\" onclick=\"newmsg('%s'); return false;\">Send Message</a>\r\n"
		"<a href=/WebMail/WMLogout?%s>Logout</a>\r\n"
		"<a href=/Mail/Header>Mail Mgmt</a>\r\n"
		"<a href=/>Node Menu</a>"
		"</nav>"
		"<div id=\"main\">\r\n"
		"%s\r\n"
		"</div> \r\n"
		"</div>"
		"</body></html>";
		"\r\n"
		"\r\n";

	return _strdup(Msg);
}


char * MainConfigtxt()
{
	static const char Msg[] =
		"<!-- Version 11 5/1/2026 Layout and port limits -->\r\n"
		"<!DOCTYPE html>\r\n"
		"<html lang=\"en\"><head>"
		"<meta charset=\"UTF-8\">"
		"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
		COMMON_BPQ_CSS_LINK
		"<title>Configuration</title>\r\n"
		"\r\n"
		"<style>"
		COMMON_PAGE_BASE_CSS
		COMMON_WEBMAIL_SHELL_980_CSS
		COMMON_WEBMAIL_TITLE_STRONG_CSS
		COMMON_SECTION_TITLE_TEXT_CSS
		"table,th,td{border:1px solid var(--border);border-collapse:collapse;}"
		"#main{" COMMON_CARD_CHROME_CSS "box-sizing:border-box;max-width:980px;margin:12px auto 0;padding:clamp(14px,2vw,22px);}"
		"#main form{font-family:" COMMON_FONT_MONO ";display:flex;flex-direction:column;}"
		".page-title{margin:10px 0 0;}"
		".section-title{margin:18px 0 10px 0;padding:8px 0;border-bottom:1px solid var(--border-light);font-weight:700;text-align:left;letter-spacing:0.2px;}"
		".section-title:first-of-type{margin-top:4px;}"
		".form-row{display:flex;align-items:flex-start;gap:12px;margin:10px 0;flex-wrap:wrap;}"
		".form-row label{flex:none;min-width:120px;text-align:left;line-height:1.35;padding-top:7px;}"
		".form-row.checkbox-row{margin:8px 0;}"
		".form-row.checkbox-row label{display:inline-flex;align-items:flex-start;gap:8px;margin:0;min-width:auto;line-height:1.35;padding-top:0;}"
		".form-row.checkbox-row input[type=checkbox]{width:18px;height:18px;margin:0;flex-shrink:0;}"
		".form-row input[type=text]{border:1px solid var(--border);background:var(--surface-soft);" COMMON_INPUT_BASE_CSS "font-family:" COMMON_FONT_MONO ";flex:none;width:220px;}"
		".form-row input[type=number]{flex:none;border:1px solid var(--border);background:var(--surface-soft);" COMMON_INPUT_BASE_CSS "font-family:" COMMON_FONT_MONO ";width:96px;max-width:100%%;}"
		".form-row input:focus-visible{outline:3px solid var(--focus-ring);outline-offset:2px;}"
		".form-row input[type=radio]{margin:0 4px 0 0;}"
		".form-row textarea{border:1px solid var(--border);background:var(--surface-soft);border-radius:6px;padding:8px 10px;box-sizing:border-box;font-family:" COMMON_FONT_MONO ";flex:1 1 300px;min-width:150px;}"
		".form-row .btn{margin-left:auto;}"
		".text-area-row{display:flex;flex-direction:column;align-items:flex-start;margin:10px 0;}"
		".text-area-row label{text-align:left;margin-bottom:4px;font-weight:500;}"
		".text-area-row textarea{width:100%%;}"
		".textarea-group{display:flex;flex-wrap:wrap;gap:10px;margin:10px 0;}"
		".textarea-col{flex:1 1 150px;display:flex;flex-direction:column;}"
		".textarea-col label{text-align:left;margin-bottom:4px;font-weight:500;font-size:0.9em;}"
		".textarea-col textarea{width:100%%;box-sizing:border-box;min-height:120px;}"
		".filter-table-wrap{overflow-x:auto;max-width:100%%;margin-top:8px;-webkit-overflow-scrolling:touch;}"
		".filter-table-wrap table{width:max-content;min-width:100%%;}"
		".filter-table-wrap th{background:var(--table-header);font-family:" COMMON_FONT_TITLE ";font-weight:600;}"
		".filter-table-wrap td{background:var(--surface);}"
		".filter-table-wrap tbody tr:nth-child(even) td{background:var(--table-stripe);}"
		".filter-table-wrap th,.filter-table-wrap td{white-space:nowrap;}"
		".filter-table-wrap td input{width:100%%;min-width:72px;box-sizing:border-box;}"
		".buttons{display:flex;justify-content:flex-end;gap:10px;margin-top:20px;}"
		".buttons input[name=Save]{background:var(--primary);border-color:var(--primary);color:var(--on-primary);}"
		".buttons input[name=Save]:hover{background:var(--primary-dark);border-color:var(--primary-dark);}"
		".buttons .btn{min-width:130px;}"
		"@media (max-width:768px){"
		"#main{padding:12px;}"
		".form-row{flex-direction:column;align-items:flex-start;gap:4px;}"
		".form-row label{flex:none;min-width:100%%;text-align:left;margin-bottom:4px;font-weight:500;width:100%%;padding-top:0;}"
		".form-row.checkbox-row{flex-direction:column;align-items:flex-start;}"
		".form-row.checkbox-row label{width:100%%;min-width:0;margin-bottom:0;}"
		".form-row input[type=text],.form-row input[type=number],.form-row textarea{width:100%%;flex:none;}"
		".form-row .btn{margin-left:0;width:100%%;}"
		".text-area-row{align-items:stretch;}"
		".text-area-row textarea{width:100%%;}"
		".textarea-group{flex-direction:column;}"
		".textarea-col{flex:none;width:100%%;}"
		".textarea-col textarea{width:100%%;}"
		".buttons{flex-direction:column;justify-content:stretch;gap:8px;}"
		".buttons .btn{flex:1 1 0;width:100%%;min-height:48px;}"
		"}"
		"</style>"
		COMMON_BPQ_JS_SCRIPT
		"</head><body>\r\n"
		"<div class=\"wm-shell\">"
		"<h2 class=\"wm-title\">BPQ32 BBS %s</h2>\r\n"
		"<div class=menu-header><button id=menuToggle class=menu-toggle type=button aria-expanded=\"false\" aria-controls=\"mailMenu\" onclick=\"toggleMenu(event)\">Menu</button></div>"
		"<div id=mailMenu class=menu>"
		"<a href=/Mail/Status?%s>Status</a>"
		"<a href=/Mail/Conf?%s>Configuration</a>"
		"<a href=/Mail/Users?%s>Users</a>"
		"<a href=/Mail/Msgs?%s>Messages</a>"
		"<a href=/Mail/FWD?%s>Forwarding</a>"
		"<a href=/Mail/Wel?%s>Welcome Msgs &amp; Prompts</a>"
		"<a href=/Mail/HK?%s>Housekeeping</a>"
		"<a href=/Mail/WP?%s>WP Update</a>"
		"<a href=/Webmail>WebMail</a>"
		"<a href=/>Node Menu</a>"
		"</div>"
		"<div class=\"section-title\">Configuration</div>"
		"\r\n"
		"<div id=\"main\">\r\n"
		"<form method=\"post\" action=\"/Mail/Config?%s\">\r\n"
		"<div class=\"section-title\">BBS Parameters</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>BBS Call</label>\r\n"
		"  <input type=\"text\" value=\"%s\" name=\"BBSCall\" size=\"8\" maxlength=\"16\">\r\n"
		"  <label>SYSOP Call</label>\r\n"
		"  <input type=\"text\" value=\"%s\" name=\"SYSOPCall\" size=\"8\" maxlength=\"16\">\r\n"
		"</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>H Route</label>\r\n"
		"  <input type=\"text\" value=\"%s\" name=\"HRoute\">\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"BBSToSYSOP\"> Redirect msgs to BBS Call to SYSOP Call</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>BBS APPL No</label>\r\n"
		"  <input type=\"number\" value=\"%d\" name=\"ApplNum\">\r\n"
		"  <label>Streams</label>\r\n"
		"  <input type=\"number\" value=\"%d\" name=\"Streams\">\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"SysToSYSOP\"> Send System Msgs to SYSOP Call</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"RefuseBulls\"> Refuse Bulls</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"EnUI\"> Enable FBB UI System</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>Send Mail For Beacons every</label>\r\n"
		"  <input type=\"number\" value=\"%d\" name=\"UIInterval\" style=\"width:80px;\">\r\n"
		"  <span style=\"white-space:nowrap;\">Minutes</span>\r\n"
		"  <input name=\"ConfigUI\" value=\"Config UI\" type=\"submit\" class=\"btn\">\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"DontHold\"> Don't Hold Messages From New Users</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"DefaultNoWinlink\"> Set Don't add WINLINK.ORG flag on new users</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"DontNeedName\"> Don't Request Name</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"DontNeedHomeBBS\"> Don't Request Home BBS</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"DontCheckFromCall\"> Don't Check From Call</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"UserCantKillT\"> Allow users to kill T messages</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"FWDtoMe\"> Forward Messages to BBS Call</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"OnlyKnown\"> Don't allow unknown users</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"Events\"> Enable Event Reporting</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>POP3 Port</label>\r\n"
		"  <input type=\"number\" value=\"%d\" name=\"POP3Port\" min=\"0\" max=\"65535\" step=\"1\">\r\n"
		"  <label>SMTP Port</label>\r\n"
		"  <input type=\"number\" value=\"%d\" name=\"SMTPPort\" min=\"0\" max=\"65535\" step=\"1\">\r\n"
		"  <label>NNTP Port</label>\r\n"
		"  <input type=\"number\" value=\"%d\" name=\"NNTPPort\" min=\"0\" max=\"65535\" step=\"1\">\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"EnRemote\"> Enable Remote Access</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>AMPR Domain</label>\r\n"
		"  <input type=\"text\" value=\"%s\" name=\"AMPRDomain\">\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"SendAMPR\"> Send AMPR Mail to AMPR host</label>\r\n"
		"</div>\r\n"
		"\r\n"
		"<div class=\"section-title\">ISP Parameters</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"EnISP\"> Enable ISP Interface</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>My Domain</label>\r\n"
		"  <input type=\"text\" value=\"%s\" name=\"ISPDomain\">\r\n"
		"</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>SMTP Server</label>\r\n"
		"  <input type=\"text\" value=\"%s\" name=\"SMTPServer\">\r\n"
		"  <label>Port</label>\r\n"
		"  <input type=\"number\" value=\"%d\" name=\"ISPSMTPPort\" min=\"0\" max=\"65535\" step=\"1\" style=\"width:80px;\">\r\n"
		"</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>SMTP Domain</label>\r\n"
		"  <input type=\"text\" value=\"%s\" name=\"ISPEHLOName\">\r\n"
		"</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>POP3 Server</label>\r\n"
		"  <input type=\"text\" value=\"%s\" name=\"POP3Server\">\r\n"
		"  <label>Port</label>\r\n"
		"  <input type=\"number\" value=\"%d\" name=\"ISPPOP3Port\" min=\"0\" max=\"65535\" step=\"1\" style=\"width:80px;\">\r\n"
		"</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>Account Name</label>\r\n"
		"  <input type=\"text\" value=\"%s\" name=\"ISPAccount\">\r\n"
		"</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>Password</label>\r\n"
		"  <input type=\"text\" value=\"%s\" name=\"ISPPassword\">\r\n"
		"</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>POP3 Poll Interval</label>\r\n"
		"  <input type=\"number\" value=\"%d\" name=\"PollInterval\" min=\"0\" max=\"9999\" step=\"1\" style=\"width:80px;\">\r\n"
		"  <span style=\"white-space:nowrap;\">Minutes</span>\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"ISPAuth\"> SMTP Server Requires Authentication</label>\r\n"
		"</div>\r\n"
		"\r\n"
		"<div class=\"section-title\">WP Parameters</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"EnWP\"> Send WP Updates</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row checkbox-row\">\r\n"
		"  <label><input %stype=\"checkbox\" name=\"RejWFBulls\"> Reject WP Bulls</label>\r\n"
		"</div>\r\n"
		"<div class=\"form-row\">\r\n"
		"  <label>Type</label>\r\n"
		"  <label><input %stype=\"radio\" name=\"Type\" value=\"TypeB\"> Type B</label>\r\n"
		"  <label><input %stype=\"radio\" name=\"Type\" value=\"TypeP\"> Type P</label>\r\n"
		"</div>\r\n"
		"<div class=\"text-area-row\">\r\n"
		"  <label>WP Destinations</label>\r\n"
		"  <textarea cols=\"40\" rows=\"4\" name=\"WPTO\">%s</textarea>\r\n"
		"</div>\r\n"
		"\r\n"
		"<div class=\"section-title\">Message Filters</div>\r\n"
		"<div style=\"text-align:left;margin:10px 0;font-size:0.9em;\">\r\n"
		"  <strong>Reject and Hold Filters:</strong> Define addresses to reject or hold messages\r\n"
		"</div>\r\n"
		"<div class=\"textarea-group\">\r\n"
		"  <div class=\"textarea-col\">\r\n"
		"    <label>Reject From</label>\r\n"
		"    <textarea cols=\"8\" rows=\"5\" name=\"Rfrom\">%s</textarea>\r\n"
		"  </div>\r\n"
		"  <div class=\"textarea-col\">\r\n"
		"    <label>Reject To</label>\r\n"
		"    <textarea cols=\"8\" rows=\"5\" name=\"Rto\">%s</textarea>\r\n"
		"  </div>\r\n"
		"  <div class=\"textarea-col\">\r\n"
		"    <label>Reject At</label>\r\n"
		"    <textarea cols=\"8\" rows=\"5\" name=\"Rat\">%s</textarea>\r\n"
		"  </div>\r\n"
		"  <div class=\"textarea-col\">\r\n"
		"    <label>Reject BID</label>\r\n"
		"    <textarea cols=\"8\" rows=\"5\" name=\"RBID\">%s</textarea>\r\n"
		"  </div>\r\n"
		"  <div class=\"textarea-col\">\r\n"
		"    <label>Hold From</label>\r\n"
		"    <textarea cols=\"8\" rows=\"5\" name=\"Hfrom\">%s</textarea>\r\n"
		"  </div>\r\n"
		"  <div class=\"textarea-col\">\r\n"
		"    <label>Hold To</label>\r\n"
		"    <textarea cols=\"8\" rows=\"5\" name=\"Hto\">%s</textarea>\r\n"
		"  </div>\r\n"
		"  <div class=\"textarea-col\">\r\n"
		"    <label>Hold At</label>\r\n"
		"    <textarea cols=\"8\" rows=\"5\" name=\"Hat\">%s</textarea>\r\n"
		"  </div>\r\n"
		"  <div class=\"textarea-col\">\r\n"
		"    <label>Hold BID</label>\r\n"
		"    <textarea cols=\"8\" rows=\"5\" name=\"HBID\">%s</textarea>\r\n"
		"  </div>\r\n"
		"</div>\r\n"
		"\r\n"
		"<div style=\"text-align:left;margin:15px 0 5px 0;font-size:0.9em;\">\r\n"
		"  <strong>FBB Reject.sys Type Filters:</strong><br>\r\n"
		"  All fields must match. Wildcards allowed. 'A' action accepts message if all fields match.\r\n"
		"</div>\r\n"
		"<div class='filter-table-wrap'>%s</div>\r\n"
		"\r\n"
		"<div class='buttons'>\r\n"
		"  <input class='btn' name=\"Save\" value=\"Save\" type=\"submit\">\r\n"
		"  <input class='btn' name=\"Cancel\" value=\"Cancel\" type=\"submit\">\r\n"
		"</div>\r\n"
		"</form>\r\n"
		"</div>\r\n"
		"</div>\r\n"
		"</body></html>\r\n";

	return _strdup(Msg);
}




char * MsgPagetxt()
{
	static const char Msg[] =
		"<!-- Version 5 3/9/2026 Desktop Layout Improved -->\r\n"
		"<!DOCTYPE html> \r\n"
		"<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\"> \r\n"
		"<head> \r\n"
		"<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\"/> \r\n"
		"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>"
		COMMON_BPQ_CSS_LINK
		"<style>"
		COMMON_PAGE_BASE_CSS
		COMMON_WEBMAIL_SHELL_1100_CSS
		COMMON_WEBMAIL_TITLE_STRONG_CSS
		COMMON_SECTION_TITLE_TEXT_CSS
		"#outer{display:grid;grid-template-columns:200px minmax(0,1fr);grid-template-rows:auto 1fr;gap:16px;min-height:%dpx;font-family: " COMMON_FONT_MONO ";align-items:start;}"
		"#main{grid-column:2;grid-row:1 / span 2;min-height:%dpx;" COMMON_CARD_CHROME_CSS "padding:20px;overflow:auto;}"
		"#sidebar{grid-column:1;grid-row:2;" COMMON_CARD_CHROME_CSS "overflow:hidden;display:flex;flex-direction:column;padding:0;max-height:calc(100vh - 280px);}"
		"#sel{grid-column:1;grid-row:1;" COMMON_CARD_CHROME_CSS "font-family: " COMMON_FONT_MONO ";padding:16px;}"
		"#sel .filter-title{text-align:center;font-weight:700;font-size:clamp(1rem,0.94rem + 0.25vw,1.125rem);margin-bottom:12px;color:var(--text);text-transform:uppercase;letter-spacing:0.5px;}"
		"#sel .filter-row{display:flex;flex-direction:column;align-items:flex-start;gap:6px;margin:0 0 12px 0;}"
		"#sel .filter-row label{font-size:clamp(0.9375rem,0.9rem + 0.2vw,1rem);font-weight:600;text-align:left;color:var(--text);text-transform:uppercase;letter-spacing:0.3px;}"
		"#sel .filter-row input{width:100%%;border:1px solid var(--border);background:var(--surface-soft);color:var(--text);border-radius:6px;padding:8px 10px;box-sizing:border-box;font-size:clamp(1rem,0.95rem + 0.2vw,1.0625rem);transition:border-color 0.15s ease,box-shadow 0.15s ease;}"
		"#sidebar table{width:100%%;border-collapse:collapse;}"
		"#sidebar td{border-bottom:1px solid var(--border-light);padding:0;}"
		"#sidebar a{display:block;padding:12px 14px;color:var(--text);text-decoration:none;font-family: " COMMON_FONT_TITLE ";font-weight:600;font-size:clamp(0.9375rem,0.9rem + 0.2vw,1rem);text-transform:uppercase;letter-spacing:0.3px;transition:background 0.15s ease;}"
		"#sidebar a:hover{background:var(--surface-soft);}"
		"#sidebar a:focus-visible{outline:3px solid var(--focus-ring);outline-offset:2px;}"
		"input[type=text],input[type=input]{" COMMON_INPUT_BASE_CSS "border:1px solid var(--border);background:var(--surface-soft);color:var(--text);border-radius:6px;font-family: " COMMON_FONT_MONO ";font-size:clamp(1rem,0.95rem + 0.2vw,1.0625rem);}"
		"input[type=text]:focus-visible,input[type=input]:focus-visible,#sel .filter-row input:focus-visible{outline:3px solid var(--focus-ring);outline-offset:2px;}"
		".msg-list{display:flex;flex-direction:column;height:100%%;min-height:0;font-family: " COMMON_FONT_MONO ";}"
		".msg-list a{font-family: " COMMON_FONT_TITLE ";}"
		".msg-list a.active{background:var(--surface-soft);border-left:3px solid var(--primary);}"
		".msg-list-toggle{display:none;width:100%%;min-height:44px;padding:10px 12px;box-sizing:border-box;border:1px solid var(--border);border-radius:6px;background:var(--surface);color:var(--text);font-weight:600;cursor:pointer;text-align:left;margin-bottom:8px;flex-shrink:0;font-family: " COMMON_FONT_TITLE ";}"
		".msg-list-body{display:block;flex:1 1 auto;overflow-y:auto;min-height:0;font-family: " COMMON_FONT_MONO ";}"
		".msg-list table{font-family: " COMMON_FONT_MONO ";}"
		".msg-list table tr:nth-child(even){background:var(--table-stripe);}"
		".msg-list table tr:hover{background:var(--surface-soft);}"
		"@media (max-width:768px){"
		"#outer{display:grid;grid-template-columns:1fr;grid-template-rows:auto auto auto;min-height:0;gap:12px;}"
		"#main{grid-column:1;grid-row:3;min-height:320px;padding:16px;}"
		"#sel{grid-column:1;grid-row:1;padding:12px;}"
		"#sel .filter-row{gap:4px;margin:10px 0;}"
		"#sel .filter-row label{min-width:100%%;font-weight:500;}"
		"#sel .filter-row input{width:100%%;min-height:44px;font-size:clamp(1rem,0.94rem + 0.25vw,1.125rem);}"
		"#sidebar{grid-column:1;grid-row:2;min-height:200px;max-height:none;padding:0;}"
		".wm-shell{max-width:none;}"
		COMMON_ADMIN_COLLAPSIBLE_LIST_MOBILE_CSS_TEMPLATE(".msg-list", ".msg-list-body", ".msg-list-toggle", ".msg-list.collapsed .msg-list-body")
		"}"
		"</style>\r\n"
		"\r\n"
		"<title>Edit Messages</title> \r\n"
		COMMON_BPQ_JS_SCRIPT
		"<script type=\"text/javascript\"> \r\n"
		" \r\n"
		"var Details\r\n"
		"var Sel\r\n"
		"var Sidebar\r\n"
		"var Outer;\r\n"
		"var CurrentMsg = \"\";\r\n"
		"var MsgListCollapsed = false;\r\n"
		"function initialize()\r\n"
		"{	\r\n"
		"resize();"
		"	Details = document.getElementById(\"main\"); \r\n"
		"	if (Details) Details.innerHTML = \"waiting for data...\"; \r\n"
		"	GetData(\"\");\r\n"
		"}\r\n"
		"function resize()\r\n"
		"{	\r\n"
		"	Outer = document.getElementById(\"outer\");\r\n"
		"	Sel = document.getElementById(\"sel\");\r\n"
		"	Sidebar = document.getElementById(\"sidebar\");\r\n"
		"	if (!Outer || !Sel || !Sidebar) return;\r\n"
		"}\r\n"
		"function isMobile(){return window.matchMedia('(max-width: 768px)').matches;}\r\n"
		"function applyMsgListState(){var listWrapper=document.querySelector('#sidebar .msg-list');if(!listWrapper)return;if(isMobile()&&MsgListCollapsed){listWrapper.classList.add('collapsed');}else{listWrapper.classList.remove('collapsed');}}\r\n"
		"function toggleMsgList(){if(!isMobile())return;MsgListCollapsed=!MsgListCollapsed;applyMsgListState();}\r\n"
		"function buildMsgList(lines){var i=0;var strInfo='<div class=\"msg-list\"><button type=button class=\"msg-list-toggle\" onclick=\"toggleMsgList()\">Messages</button><div class=\"msg-list-body\"><table>';while(i < lines.length - 1){var active=(lines[i]===CurrentMsg)?' class=\"active\"':'';var clink='<a'+active+' href=\\'javascript:GetDetails(\\\"'+lines[i]+'\\\",false)\\'>'+lines[i]+'</a>';strInfo += '<tr><td>' + clink + '</td></tr>';i=i+1;}return strInfo + '</table></div></div>';}\r\n"

		"function ck(cell)\r\n"
		"{\r\n"
		"	var fn = \"MsgFwdUpdate?%s\";\r\n"
		"	post(fn, cell);\r\n"
		"}\r\n"
		"\r\n"
		"function save(form)\r\n"
		"{\r\n"
		"\tvar msg\r\n"
		"\tvar efrom = form.EFROM ? form.EFROM.value : \"\";\r\n"
		"\tmsg = form.From.value + \"|\" + form.To.value+ \"|\" + form.BID.value+ \"|\" + efrom + \"|\" + form.VIA.value+ \"|\" + form.Title.value+ \"|\" + form.Type.value + \"|\" + form.Status.value +\"|\"\r\n"
		"	var fn = \"MsgSave?%s\";\r\n"
		"	post(fn, msg);\r\n"
		"}\r\n"
		"\r\n"
		"function doit(param)\r\n"
		"{\r\n"
		"	var fn = \"MsgAction?%s\";\r\n"
		"	post(fn, param);\r\n"
		"}\r\n"
		"\r\n"
		"function dofilter(form)\r\n"
		"{\r\n"
		"	var val = form.FFrom.value + \"|\" + form.FTo.value + \"|\" + form.FVia.value+ \"|\" + form.FBid.value+ \"|\" \r\n"
		"	GetData(val);\r\n"
		"}\r\n"
		"\r\n"
		"function editmsg(url)\r\n"
		"{\r\n"
		"var param = \"toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=no,titlebar=no,toobar=no,width=800,height=600\";\r\n"
		"window.open(url,\"_blank\", param);\r\n"
		"}\r\n"
		"\r\n"
		"\r\n"
		"function post(url, data)\r\n"
		"{\r\n"
		"	if (window.XMLHttpRequest){request=new XMLHttpRequest();}else{request=new ActiveXObject(\"Microsoft.XMLHTTP\");}\r\n"
		"	request.onreadystatechange = function()\r\n"
		"	{if (request.readyState == 4){Details.innerHTML = request.responseText;}}\r\n"
		"	request.open(\"POST\", url, true);request.send(data);\r\n"
		"}\r\n"
		"function GetDetails(call, autoSelect)\r\n"
		"{\r\n"
		"	CurrentMsg = call;\r\n"
		"	if (!autoSelect && isMobile()) { MsgListCollapsed = true; applyMsgListState(); }\r\n"
		"	var fn = \"MsgDetails?%s\";\r\n"
		"	post(fn, call);\r\n"
		"}\r\n"
		"function GetData(filter)\r\n"
		"{\r\n"
		"	if (window.XMLHttpRequest){request=new XMLHttpRequest();}else{request=new ActiveXObject(\"Microsoft.XMLHTTP\");}\r\n"
		" \r\n"
		"	request.onreadystatechange = function()\r\n"
		"	{\r\n"
		"		if (request.readyState == 4)\r\n"
		"		{\r\n"
		"			var text = request.responseText;\r\n"
		"			var lines = text.split(\"|\");\r\n"
		"			var i = 0;\r\n"
		"			\r\n"
		"	 	    var infoArea = document.getElementById(\"sidebar\"); \r\n"
		"		    infoArea.innerHTML = buildMsgList(lines);\r\n"
		"		    applyMsgListState();\r\n"
		"		    GetDetails(lines[0], true);\r\n"
		"		}\r\n"
		"	}\r\n"
		"	request.open(\"POST\",\"MsgInfo.txt?%s\",true);										   \r\n"
		"	request.send(filter);\r\n"
		"}\r\n"
		"window.addEventListener('resize', function(){ if (!isMobile()) MsgListCollapsed = false; applyMsgListState(); });\r\n"
		" \r\n"
		"</script>\r\n"
		"</head>\r\n"
		"<body onload=\"initialize()\" onresize=\"resize()\">\r\n"
		"<div class=\"wm-shell\">"
		"<h2 class=\"wm-title\">BPQ32 BBS %s</h2>\r\n"
		"<div class=\"menu-header\"><button id=\"menuToggle\" class=\"menu-toggle\" type=\"button\" aria-expanded=\"false\" aria-controls=\"mainMenu\" onclick=\"toggleMenu(event)\">Menu</button></div>"
		"<nav id=\"mainMenu\" class=\"menu\">"
		"<a href=\"/Mail/Status?%s\">Status</a>\r\n"
		"<a href=\"/Mail/Conf?%s\">Configuration</a>\r\n"
		"<a href=\"/Mail/Users?%s\">Users</a>\r\n"
		"<a href=\"/Mail/Msgs?%s\">Messages</a>\r\n"
		"<a href=\"/Mail/FWD?%s\">Forwarding</a>\r\n"
		"<a href=\"/Mail/Wel?%s\">Welcome Msgs &amp; Prompts</a>\r\n"
		"<a href=\"/Mail/HK?%s\">Housekeeping</a>\r\n"
		"<a href=\"/Mail/WP?%s\">WP Update</a>\r\n"
		"<a href=/Webmail>WebMail</a>"
		"<a href=\"/\">Node Menu</a>\r\n"
		"</nav>\r\n"
		"<div class=\"section-title\">Message Management</div>\r\n"
		"\r\n"
		"<div id=\"outer\">\r\n"
		" <div id=\"sidebar\"></div>\r\n"
		" <div id=\"main\"></div> \r\n"
		" <div id=\"sel\">\r\n"
		"  <form>\r\n"
		"   <div class=\"filter-title\">Filter</div>\r\n"
		"   <div class=\"filter-row\">\r\n"
		"    <label>From</label>\r\n"
		"    <input type=\"text\" name=\"FFrom\" value=\"\" onkeyup=\"dofilter(this.form)\">\r\n"
		"   </div>\r\n"
		"   <div class=\"filter-row\">\r\n"
		"    <label>To</label>\r\n"
		"    <input type=\"text\" name=\"FTo\" value=\"\" onkeyup=\"dofilter(this.form)\">\r\n"
		"   </div>\r\n"
		"   <div class=\"filter-row\">\r\n"
		"    <label>Via</label>\r\n"
		"    <input type=\"text\" name=\"FVia\" value=\"\" onkeyup=\"dofilter(this.form)\">\r\n"
		"   </div>\r\n"
		"   <div class=\"filter-row\">\r\n"
		"    <label>BID</label>\r\n"
		"    <input type=\"text\" name=\"FBid\" value=\"\" onkeyup=\"dofilter(this.form)\">\r\n"
		"   </div>\r\n"
		"  </form>\r\n"
		" </div>\r\n"
		"</div> \r\n"
		"</span>\r\n"
		"</div>\r\n"
		"\r\n";

	return _strdup(Msg);
}



char * UserDetailtxt()
{
	static const char Msg[] =
		"<!-- Version 7 5/2/2026 Shared stats table layout -->\r\n"
		"<form method=\"post\" action=\"/Mail/UserSave?%s\">\r\n"
		"<h3>Update User %s</h3>\r\n"
		"<div class='detail-grid'>"
		"<label class='detail-item'><input %sname=\"BBS\" type=\"checkbox\">BBS</label>"
		"<label class='detail-item'><input %s name=\"PermitEmail\" type=\"checkbox\">Permit Email</label>"
		"<label class='detail-item'><input %sname=\"PMS\" type=\"checkbox\">PMS</label>"
		"<label class='detail-item'><input %sname=\"RMSExUser\" type=\"checkbox\">RMS Express User</label>"
		"<label class='detail-item'><input %sname=\"SYSOP\" type=\"checkbox\">SYSOP</label>"
		"<label class='detail-item'><input %s name=\"PollRMS\" type=\"checkbox\">Poll RMS</label>"
		"<label class='detail-item'><input %sname=\"Expert\" type=\"checkbox\">Expert</label>"
		"<div class='ssid-row'>For SSID's"
		"<input style=\"width: 24px;\" name=\"SSID1\" value=\"%s\">"
		"<input style=\"width: 24px;\" name=\"SSID2\" value=\"%s\">"
		"<input style=\"width: 24px;\" name=\"SSID3\" value=\"%s\">"
		"<input style=\"width: 24px;\" name=\"SSID4\" value=\"%s\"></div>"
		"<label class='detail-item'><input %sname=\"Excluded\" type=\"checkbox\">Excluded</label>"
		"<label class='detail-item'><input %sname=\"Hold\" type=\"checkbox\">Hold Messages</label>"
		"<label class='detail-item'><input %sname=\"SYSOPLM\" type=\"checkbox\">Include SYSOP msgs in LM</label>"
		"<label class='detail-item'><input %sname=\"NOWINLINK\" type=\"checkbox\">Don't add @winlink.org</label>"
		"<label class='detail-item'><input %sname=\"ALLOWBULLS\" type=\"checkbox\">Allow Sending Bulls</label>"
		"<label class='detail-item'><input %sname=\"NTSMPS\" type=\"checkbox\">NTS MPS</label>"
		"<label class='detail-item'><input %sname=\"RMSREDIR\" type=\"checkbox\">Redirect to RMS</label>"
		"<div class='ssid-row'><label class='detail-item'><input %sname=APRSMFOR type=checkbox>Send APRS Mail For to SSID</label>"
		"<input style=\"width: 24px;\" name=APRSSSID value=%s></div>"
		"</div>"
		"  <div class='table-wrap stats-wrap'><table class='node-table node-table-stack compact-table stats-table'>\r\n"
		"    <tbody>\r\n"
		"      <tr>\r\n"
		"        <td data-label='Metric' class='text'>Connects In</td>\r\n"
		"        <td data-label='Value' class='num'>%d</td>\r\n"
		"        <td data-label='Metric' class='text'>Msgs In</td>\r\n"
		"        <td data-label='Value' class='num'>%d</td>\r\n"
		"        <td data-label='Metric' class='text'>Rejects In</td>\r\n"
		"        <td data-label='Value' class='num'>%d</td>\r\n"
		"      </tr>\r\n"
		"      <tr>\r\n"
		"        <td data-label='Metric' class='text'>Connects Out</td>\r\n"
		"        <td data-label='Value' class='num'>%d</td>\r\n"
		"        <td data-label='Metric' class='text'>Msgs Out</td>\r\n"
		"        <td data-label='Value' class='num'>%d</td>\r\n"
		"        <td data-label='Metric' class='text'>Rejects Out</td>\r\n"
		"        <td data-label='Value' class='num'>%d</td>\r\n"
		"      </tr>\r\n"
		"      <tr>\r\n"
		"        <td data-label='Metric' class='text'>Bytes In</td>\r\n"
		"        <td data-label='Value' class='num'>%d</td>\r\n"
		"        <td data-label='Metric' class='text'>Last Connect</td>\r\n"
		"        <td data-label='Value' class='text' colspan=\"3\">%s</td>\r\n"
		"      </tr>\r\n"
		"      <tr>\r\n"
		"        <td data-label='Metric' class='text'>Bytes Out</td>\r\n"
		"        <td data-label='Value' class='num'>%d</td>\r\n"
		"        <td data-label='Metric' class='text'></td>\r\n"
		"        <td data-label='Value' class='text'></td>\r\n"
		"        <td data-label='Metric' class='text'>Last Listed</td>\r\n"
		"        <td data-label='Value' class='num'>%d</td>\r\n"
		"      </tr>\r\n"
		"    </tbody>\r\n"
		"  </table></div>\r\n"
		"<div class='form-row'><label for='Name'>Name:</label><input class='text' id='Name' name='Name' value='%s'></div>\r\n"
		"<div class='form-row'><label for='Password'>Password:</label><input class='text' id='Password' name='Password' value='%s'></div>\r\n"
		"<div class='form-row'><label for='CMSPass'>CMS Pass:</label><input class='text' id='CMSPass' name='CMSPass' value='%s'></div>\r\n"
		"<div class='form-row split-row'><label for='QTH'>QTH:</label><input class='text' id='QTH' name='QTH' value='%s'><label for='ZIP'>ZIP:</label><input class='text' id='ZIP' name='ZIP' value='%s'></div>\r\n"
		"<div class='form-row'><label for='HomeBBS'>Home BBS:</label><input class='text' id='HomeBBS' name='HomeBBS' value='%s'></div>\r\n"
		"<div class='actions'><input class='btn' onclick=save(this.form) value=Update type=button>\r\n"
		"<input class='btn' onclick=del(this.form) value=Delete type=button>\r\n"
		"<input class='btn' onclick=add(this.form) value=Add type=button>\r\n"
		"<input class='newcall' name='NewCall'></div>\r\n"
		"</form>\r\n"
		"\r\n";

	return _strdup(Msg);
}


char * UserPagetxt()
{
	static const char Msg[] =
		"<!-- Version 6 3/9/2026 Refactored -->\r\n"
		"<!DOCTYPE html> \r\n"
		"<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\"> \r\n"
		"<head> \r\n"
		"<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\"/> \r\n"
		"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>"
		COMMON_BPQ_CSS_LINK
		"<style>"
		COMMON_PAGE_BASE_CSS
		COMMON_TABLE_CSS
		COMMON_WEBMAIL_SHELL_980_CSS
		COMMON_WEBMAIL_TITLE_STRONG_CSS
		COMMON_SECTION_TITLE_CSS
		"#outer{display:grid;grid-template-columns:220px minmax(0,1fr);grid-template-areas:'sidebar main';gap:12px;width:100%%;margin-top:12px;align-items:start;}"
		"#sidebar{grid-area:sidebar;display:flex;flex-direction:column;overflow:hidden;max-height:calc(100vh - 260px);}"
		"#main{grid-area:main;overflow:auto;}"
		"#sidebar,#main{background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:10px;}"
		"#sidebar a.active{background:var(--surface-soft);}"
		".user-list{display:flex;flex-direction:column;height:100%%;min-height:0;}"
		COMMON_ADMIN_LIST_TOGGLE_CSS_TEMPLATE(".user-list-toggle")
		".user-list-toggle{font-family: " COMMON_FONT_TITLE ";}"
		COMMON_ADMIN_LIST_BODY_CSS_TEMPLATE(".user-list-body")
		".user-list-body{max-height:none;}"
		".user-list table tr:nth-child(even){background:var(--table-stripe);}"
		"#sidebar table{width:100%%;border-collapse:collapse;}"
		"#sidebar td{border-bottom:1px solid var(--border-light);padding:0;}"
		"#sidebar a{display:block;padding:8px 10px;color:var(--text);text-decoration:none;font-family: " COMMON_FONT_TITLE ";font-weight:600;text-transform:uppercase;}"
		"#sidebar a:hover{background:var(--surface-soft);}"
		"#main form{font-family: " COMMON_FONT_MONO ";line-height:1.35;}"
		"#main h3{margin:0 0 10px;text-align:center;}"
		"#main form > div:first-of-type{position:static !important;left:auto !important;}"
		"#main table{max-width:100%%;}"
		"#main td{vertical-align:middle;}"
		"#main .detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px 14px;margin-bottom:10px;}"
		"#main .detail-item{display:flex;align-items:center;gap:8px;min-height:30px;}"
		"#main .ssid-row{grid-column:1 / -1;display:flex;align-items:center;gap:8px;flex-wrap:wrap;}"
		"#main .stats-wrap{max-width:100%%;margin:14px 0;}"
		"#main .stats-table{width:100%%;margin:0;font-size:" COMMON_TABLE_FONT_SIZE_COMPACT ";}"
		"#main .stats-table td{padding:6px 8px;}"
		"#main .form-row{display:flex;align-items:center;gap:10px;margin:8px 0;flex-wrap:wrap;}"
		"#main .form-row label{flex:0 0 110px;font-weight:600;}"
		"#main .form-row .grow{flex:1 1 260px;min-width:220px;}"
		"#main .form-row.split-row .zip-label{flex:0 0 42px;}"
		"#main .form-row .zip{flex:0 0 120px;max-width:120px;}"
		"#main .actions{display:flex;align-items:center;justify-content:flex-end;gap:10px;flex-wrap:wrap;margin-top:12px;}"
		"#main .actions .newcall{width:90px;text-transform:uppercase;}"
		"#main input[type=text],#main input[type=password],#main input:not([type]){" COMMON_INPUT_BASE_CSS "border:1px solid var(--border);background:var(--surface-soft);color:var(--text);border-radius:6px;max-width:100%%;}"
		"#main input[type=text]:focus-visible,#main input[type=password]:focus-visible,#main input:not([type]):focus-visible{outline:3px solid var(--focus-ring);outline-offset:2px;}"
		"#main input[type=checkbox]{transform:translateY(1px);}"
		"@media (max-width:768px){#outer{grid-template-columns:1fr;grid-template-areas:'sidebar' 'main';align-items:stretch;}#sidebar,#main{min-height:0;}#sidebar{max-height:none;}" COMMON_ADMIN_COLLAPSIBLE_LIST_MOBILE_CSS_TEMPLATE(".user-list", ".user-list-body", ".user-list-toggle", "#sidebar.collapsed .user-list-body") "#main .detail-grid{grid-template-columns:1fr;}#main .form-row{flex-direction:column;align-items:stretch;}#main .form-row label{flex:none;}#main .form-row .zip{max-width:none;}#main .actions{justify-content:stretch;}#main .actions .btn,#main .actions .newcall{width:100%%;}#main input[type=text],#main input[type=password],#main input:not([type]),.btn{min-height:48px;width:100%%;}}"
		"</style>\r\n"
		"\r\n"
		"<title>Edit Users</title> \r\n"
		COMMON_BPQ_JS_SCRIPT
		"<script type=\"text/javascript\"> \r\n"
		"var Details\r\n"
		"var Sidebar\r\n"
		"var CurrentCall = \"\";\r\n"
		"var UserListCollapsed = false;\r\n"
		"var Key = \"%s\"\r\n"
		"function isMobile(){return window.matchMedia('(max-width: 768px)').matches;}\r\n"
		"function applyUserListState(){var listWrapper=document.querySelector('#sidebar .user-list');if(!listWrapper)return;if(isMobile()&&UserListCollapsed){listWrapper.classList.add('collapsed');}else{listWrapper.classList.remove('collapsed');}}\r\n"
		"function toggleUserList(){if(!isMobile())return;UserListCollapsed=!UserListCollapsed;applyUserListState();}\r\n"
		"function buildUserList(lines){var i=0;var strInfo='<div class=\"user-list\"><button type=button class=\"user-list-toggle\" onclick=\"toggleUserList()\">Users</button><div class=\"user-list-body\"><table>';while(i < lines.length - 1){var active=(lines[i]===CurrentCall)?' class=\"active\"':'';var clink='<a'+active+' href=\\'javascript:GetDetails(\"'+lines[i]+'\",false)\\'>'+lines[i]+'</a>';strInfo += '<tr><td>' + clink + '</td></tr>';i=i+1;}return strInfo + '</table></div></div>'; }\r\n"
		"\r\n"
		"function initialize()\r\n"
		"{\r\n"

		"	Details = document.getElementById(\"main\"); \r\n"
		"	Details.innerHTML = \"waiting for data...\"; \r\n"
		"	GetData(\"\");\r\n"
		"}\r\n"
		"\r\n"
		"function resize()\r\n"
		"{\r\n"
		"\treturn;\r\n"
		"}\r\n"
		"\r\n"
		"function save(form)\r\n"
		"{\r\n"
		"	var msg\r\n"
		"	var fn = \"UserSave?\" + Key;\r\n"
		"	\r\n"
		"	msg = \r\n"
		"	form.BBS.checked + \"|\" +\r\n"
		"	form.PermitEmail.checked + \"|\" + \r\n"
		"	form.PMS.checked + \"|\" +\r\n"
		"	form.RMSExUser.checked + \"|\" +\r\n"
		"	form.SYSOP.checked + \"|\" +\r\n"
		"	form.PollRMS.checked + \"|\" +\r\n"
		"	form.Expert.checked + \"|\" +\r\n"
		"	form.SSID1.value + \"|\" +\r\n"
		"	form.SSID2.value + \"|\" +\r\n"
		"	form.SSID3.value + \"|\" +\r\n"
		"	form.SSID4.value + \"|\" +\r\n"
		"	form.Excluded.checked + \"|\" +\r\n"
		"	form.Hold.checked + \"|\" +\r\n"
		"	form.SYSOPLM.checked + \"|\" +\r\n"
		"	form.NOWINLINK.checked + \"|\" +\r\n"
		"	form.ALLOWBULLS.checked + \"|\" +\r\n"
		"	form.NTSMPS.checked + \"|\" +\r\n"
		"	form.RMSREDIR.checked + \"|\" +\r\n"
		"	form.APRSMFOR.checked + \"|\" +\r\n"
		"	form.APRSSSID.value + \"|\" +\r\n"
		"	form.LastListed.value + \"|\" +\r\n"
		"	form.Name.value + \"|\" +\r\n"
		"	form.Password.value + \"|\"  +\r\n"
		"	form.CMSPass.value + \"|\"  +\r\n"
		"	form.QTH.value + \"|\" + \r\n"
		"	form.ZIP.value + \"|\" + \r\n"
		"	form.HomeBBS.value + \"|\"\r\n"
		"	post(fn, msg);\r\n"
		"}\r\n"
		"\r\n"
		"function del(form)\r\n"
		"{\r\n"
		"	var fn = \"UserSave?\" + Key;\r\n"
		"	xpost(fn, \"Delete\", \"\");\r\n"
		"}\r\n"
		"\r\n"
		"function add(form)\r\n"
		"{\r\n"
		"	var fn = \"UserSave?\" + Key;\r\n"
		"	xpost(fn, \"Add=\" + form.NewCall.value, form.NewCall.value);\r\n"
		"}\r\n"
		"\r\n"
		"function post(url, data)\r\n"
		"{\r\n"
		"	if (window.XMLHttpRequest){request=new XMLHttpRequest();}else{request=new ActiveXObject(\"Microsoft.XMLHTTP\");}\r\n"
		"	request.onreadystatechange = function()\r\n"
		"	{if (request.readyState == 4){Details.innerHTML = request.responseText;}}\r\n"
		"	request.open(\"POST\", url, true);request.send(data);\r\n"
		"}\r\n"
		"\r\n"
		"function xpost(url, data, call)\r\n"
		"{\r\n"
		"\tif (window.XMLHttpRequest){request=new XMLHttpRequest();}else{request=new ActiveXObject(\"Microsoft.XMLHTTP\");}\r\n"
		"\trequest.onreadystatechange = function()\r\n"
		"\t{if (request.readyState == 4){\r\n"
		"\t{\r\n"
		"\t\t\tvar text = request.responseText;\r\n"
		"\t\t\tvar lines = text.split(\"|\");\r\n"
		"\t\t\tvar selected = call || lines[0] || '';\r\n"
		"\t\t\t\r\n"
		"\t \t    var infoArea = document.getElementById(\"sidebar\"); \r\n"
		"\t\t\tCurrentCall = selected;\r\n"
		"\t\t\tinfoArea.innerHTML = buildUserList(lines);\r\n"
		"\t\t\tapplyUserListState();\r\n"
		"\t\t\t\r\n"
		"\t\t\tif (selected)\r\n"
		"\t\t\t{\r\n"
		"\t\t\t\tGetDetails(selected, true);\r\n"
		"\t\t\t}\r\n"
		"\t\t\telse if (Details)\r\n"
		"\t\t\t{\r\n"
		"\t\t\t\tDetails.innerHTML = 'No users found.';\r\n"
		"\t\t\t}\r\n"
		"\t\t}\r\n"
		"\t\r\n"
		"\t\r\n"
		"\t}}\r\n"
		"\trequest.open(\"POST\", url, true);request.send(data);\r\n"
		"}\r\n"
		"function GetDetails(call, autoSelect)\r\n"
		"{\r\n"
		"	CurrentCall = call;\r\n"
		"	if (!autoSelect && isMobile()) { UserListCollapsed = true; applyUserListState(); }\r\n"
		"	var fn = \"UserDetails?\" + Key;\r\n"
		"	post(fn, call);\r\n"
		"}\r\n"
		"function GetData()\r\n"
		"{\r\n"
		"\tif (window.XMLHttpRequest){request=new XMLHttpRequest();}else{request=new ActiveXObject(\"Microsoft.XMLHTTP\");}\r\n"
		" \r\n"
		"\trequest.onreadystatechange = function()\r\n"
		"\t{\r\n"
		"\t\tif (request.readyState == 4)\r\n"
		"\t\t{\r\n"
		"\t\t\tvar text = request.responseText;\r\n"
		"\t\t\tvar lines = text.split(\"|\");\r\n"
		"\t\t\t\r\n"
		"\t \t    var infoArea = document.getElementById(\"sidebar\"); \r\n"
		"\t\t    infoArea.innerHTML = buildUserList(lines);\r\n"
		"\t\t    applyUserListState();\r\n"
		"\t\t    if (lines[0]) GetDetails(lines[0], true); else Details.innerHTML = 'No users found.';\r\n"
		"\t\t}\r\n"
		"\t}\r\n"
		"\trequest.open(\"POST\",\"UserList.txt?%s\",true);\t\t\t\t\t\t\t   \r\n"
		"\trequest.send();\r\n"
		"}\r\n"
		"window.addEventListener('resize', function(){ if (!isMobile()) UserListCollapsed = false; applyUserListState(); });\r\n"
		" \r\n"
		"</script>\r\n"
		"</head>\r\n"
		"<body onload=\"initialize()\" onresize=\"resize()\">\r\n"
		"<div class=\"wm-shell\">"
		"<h2 class=\"wm-title\">BPQ32 BBS %s</h2>\r\n"
		"<div class=\"menu-header\"><button id=\"menuToggle\" class=\"menu-toggle\" type=\"button\" onclick=\"toggleMenu(event)\">Menu</button></div>"
		"<div id=\"mailMenu\" class=\"menu\">"
		"<a href=/Mail/Status?%s>Status</a>\r\n"
		"<a href=/Mail/Conf?%s>Configuration</a>\r\n"
		"<a href=/Mail/Users?%s>Users</a>\r\n"
		"<a href=/Mail/Msgs?%s>Messages</a>\r\n"
		"<a href=/Mail/FWD?%s>Forwarding</a>\r\n"
		"<a href=/Mail/Wel?%s>Welcome Msgs & Prompts</a>\r\n"
		"<a href=/Mail/HK?%s>Housekeeping</a>\r\n"
		"<a href=/Mail/WP?%s>WP Update</a>\r\n"
		"<a href=/Webmail>WebMail</a>"
		"<a href=/>Node Menu</a>"
		"</div>"
		"<div class=\"section-title\">User Management</div>\r\n"
		"<div id=\"outer\">\r\n"
		" <div id=\"sidebar\"></div>\r\n"
		" <div id=\"main\"></div> \r\n"
		"</div> \r\n"
		"</div>\r\n"
		"\r\n"
		"\r\n";

	return _strdup(Msg);
}



char * Housekeepingtxt()
{
	static const char Msg[] =
		"<!-- Version 4 3/9/2026 Refactored -->\r\n"
		"<!DOCTYPE html>\r\n"
		"<html lang=\"en\"><head>\r\n"
		"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
		"<meta charset=\"UTF-8\">\r\n"
		"<title>Housekeeping</title>\r\n"
		COMMON_BPQ_CSS_LINK
		"<style>"
		COMMON_PAGE_BASE_CSS
		".hk-container{max-width:980px;margin:0 auto;}"
		".hk-title{text-align:center;font-family:" COMMON_FONT_TITLE ";font-size:clamp(1.25rem,1.05rem + 0.9vw,1.75rem);font-weight:700;margin:12px 0 0;color:var(--text);}"
		".hk-layout{display:flex;gap:20px;flex-wrap:wrap;}"
		".hk-params{flex:0 0 280px;background:var(--surface);padding:15px;border:1px solid var(--border);border-radius:8px;box-shadow:var(--shadow-card);}"
		".hk-params h4{text-align:center;margin:0 0 15px;font-size:1.1em;}"
		".hk-lifetimes{flex:1 1 500px;min-width:0;background:var(--surface);padding:15px;border:1px solid var(--border);border-radius:8px;box-shadow:var(--shadow-card);}"
		".hk-lifetimes h4{text-align:center;margin:0 0 15px;font-size:1.1em;}"
		".hk-form-row{display:flex;flex-wrap:wrap;margin:10px 0;gap:10px;align-items:center;}"
		".hk-form-row label{flex:1 1 150px;}"
		".hk-form-row input[type=text],.hk-form-row input[type=number]{flex:0 0 80px;" COMMON_INPUT_BASE_CSS "border:1px solid var(--border);background:var(--surface-soft);color:var(--text);}"
		".hk-form-row input[type=checkbox]{margin:0 5px;}"
		".hk-table{table-layout:auto;width:auto;margin:10px 0;}"
		".hk-table td{padding:5px;}"
		".hk-table input{width:65px;" COMMON_INPUT_BASE_CSS "border:1px solid var(--border);background:var(--surface-soft);color:var(--text);}"
		".hk-lifetime-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:15px;margin:15px 0;}"
		".hk-lifetime-box{border:1px solid var(--border);border-radius:6px;padding:12px;background:var(--surface-soft);}"
		".hk-lifetime-box h5{text-align:center;margin:0 0 10px;font-size:1em;}"
		".hk-lifetime-box .hk-form-row{margin:8px 0;}"
		".hk-lifetime-box .hk-form-row label{flex:1 1 auto;}"
		".hk-lifetime-box .hk-form-row input{flex:0 0 60px;}"
		".hk-override-section{margin-top:20px;padding:15px;border-top:1px solid var(--border-light);}"
		".hk-override-section p{margin:0 0 10px;font-size:0.9em;color:var(--text);}"
		".hk-textarea-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px;margin:10px 0;}"
		".hk-textarea-grid label{display:block;font-weight:bold;margin-bottom:5px;text-align:center;}"
		".hk-textarea-grid textarea{width:100%%;min-height:120px;padding:8px;border:1px solid var(--border);background:var(--surface-soft);color:var(--text);border-radius:6px;font-family: " COMMON_FONT_MONO ";font-size:clamp(0.9375rem,0.9rem + 0.2vw,1rem);resize:vertical;}"
		".hk-form-row input[type=text]:focus-visible,.hk-form-row input[type=number]:focus-visible,.hk-table input:focus-visible,.hk-textarea-grid textarea:focus-visible{outline:3px solid var(--focus-ring);outline-offset:2px;}"
		".hk-buttons{display:flex;gap:10px;justify-content:center;margin-top:20px;flex-wrap:wrap;}"
		".hk-buttons input{background:var(--surface);color:var(--text);padding:10px 20px;border:1px solid var(--border);border-radius:6px;cursor:pointer;min-height:44px;font-size:clamp(1rem,0.94rem + 0.25vw,1.125rem);}"
		".hk-buttons input[name=RunNow],.hk-buttons input[name=Save]{background:var(--primary);border-color:var(--primary);color:var(--on-primary);}"
		".hk-buttons input:hover{background:var(--surface-hover);}"
		".hk-buttons input[name=RunNow]:hover,.hk-buttons input[name=Save]:hover{background:var(--primary-dark);border-color:var(--primary-dark);}"
		".hk-buttons input:focus-visible{outline:3px solid var(--focus-ring);outline-offset:2px;}"
		"@media (max-width:768px){"
		".hk-layout{flex-direction:column;}"
		".hk-params{flex:none;width:100%%;}"
		".hk-form-row{flex-direction:column;align-items:flex-start;}"
		".hk-form-row label{flex:none;width:100%%;}"
		".hk-form-row input[type=text],.hk-form-row input[type=number]{flex:none;width:100%%;}"
		".hk-lifetime-grid{grid-template-columns:1fr;}"
		".hk-textarea-grid{grid-template-columns:1fr;}"
		".hk-buttons{flex-direction:column;}"
		".hk-buttons input{width:100%%;}"
		"}"
		"</style>"
		"</head>\r\n"
		"<body>\r\n"
		"<div class=\"hk-container\">\r\n"
		"<div class=\"hk-title\">Housekeeping</div>\r\n"
		"\r\n"
		"<form method=\"post\" action=\"/Mail/HK?%s\" name=\"HK\">\r\n"
		"<div class=\"hk-layout\">\r\n"
		"<div class=\"hk-params\">\r\n"
		"<h4>Parameters</h4>\r\n"
		"<table class=\"hk-table\">\r\n"
		"<tr><td>Maintenance Time (UTC)</td><td><input type=\"number\" name=\"MTTime\" value=\"%04d\" /></td></tr>\r\n"
		"<tr><td>Maintenance Interval (Hrs)</td><td><input type=\"number\" name=\"MTInt\" value=\"%d\" /></td></tr>\r\n"
		"<tr><td>Max Message Number</td><td><input type=\"number\" name=\"MAXMSG\" value=\"%d\" /></td></tr>\r\n"
		"<tr><td>BID Lifetime (Days)</td><td><input type=\"number\" name=\"BIDLife\" value=\"%d\" /></td></tr>\r\n"
		"<tr><td>Log File Lifetime (Days)</td><td><input type=\"number\" name=\"LogLife\" value=\"%d\" /></td></tr>\r\n"
		"<tr><td>Delete Inactive Users (Days)</td><td><input type=\"number\" name=\"UserLife\" value=\"%d\" /></td></tr>\r\n"
		"</table>\r\n"
		"<div class=\"hk-form-row\"><label>Delete Messages and logs to recycle bin</label><input %sname=\"Deltobin\" value=\"Deltobin\" type=\"checkbox\"></div>\r\n"
		"<div class=\"hk-form-row\"><label>Send Non-delivery Notifications for P and T messages</label><input %sname=\"SendND\" value=\"SendND\" type=\"checkbox\" /></div>\r\n"
		"<div class=\"hk-form-row\"><label>Suppress Mailing of Housekeeping Result</label><input %sname=\"NoMail\" value=\"Yes\" type=\"checkbox\"></div>\r\n"
		"<div class=\"hk-form-row\"><label>Generate Traffic Report</label><input %sname=\"GenTraffic\" value=\"Yes\" type=\"checkbox\"></div>\r\n"
		"<div class=\"hk-buttons\"><input name=\"RunNow\" value=\"Run Housekeeping\" type=\"submit\" class='btn'></div>\r\n"
		"</div>\r\n"
		"\r\n"
		"<div class=\"hk-lifetimes\">\r\n"
		"<h4>Lifetimes (Days)</h4>\r\n"
		"<div class=\"hk-lifetime-grid\">\r\n"
		"<div class=\"hk-lifetime-box\">\r\n"
		"<h5>Personals</h5>\r\n"
		"<div class=\"hk-form-row\"><label>Read</label><input type=\"text\" name=\"PR\" value=\"%.2f\"></div>\r\n"
		"<div class=\"hk-form-row\"><label>Unread</label><input type=\"text\" name=\"PUR\" value=\"%.2f\"></div>\r\n"
		"<div class=\"hk-form-row\"><label>Forwarded</label><input type=\"text\" name=\"PF\" value=\"%.2f\"></div>\r\n"
		"<div class=\"hk-form-row\"><label>Unforwarded</label><input type=\"text\" name=\"PUF\" value=\"%.2f\"></div>\r\n"
		"</div>\r\n"
		"<div class=\"hk-lifetime-box\">\r\n"
		"<h5>Bulletins</h5>\r\n"
		"<div class=\"hk-form-row\"><label>Forwarded</label><input type=\"text\" name=\"BF\" value=\"%d\"></div>\r\n"
		"<div class=\"hk-form-row\"><label>Unforwarded</label><input type=\"text\" name=\"BUF\" value=\"%d\"></div>\r\n"
		"</div>\r\n"
		"<div class=\"hk-lifetime-box\">\r\n"
		"<h5>NTS</h5>\r\n"
		"<div class=\"hk-form-row\"><label>Delivered</label><input type=\"text\" name=\"NTSD\" value=\"%d\"></div>\r\n"
		"<div class=\"hk-form-row\"><label>Forwarded</label><input type=\"text\" name=\"NTSF\" value=\"%d\"></div>\r\n"
		"<div class=\"hk-form-row\"><label>Unforwarded</label><input type=\"text\" name=\"NTSU\" value=\"%d\"></div>\r\n"
		"</div>\r\n"
		"</div>\r\n"
		"\r\n"
		"<div class=\"hk-override-section\">\r\n"
		"<p>The following boxes allow you to specify different values for different Bulletin origins and destinations. Normally these apply to Sent Messages. To apply to unsent, check box below.</p>\r\n"
		"<p>Specify Call, Lifetime....eg ALL, 10</p>\r\n"
		"<div class=\"hk-textarea-grid\">\r\n"
		"<div><label>From</label><textarea name=\"From\">%s</textarea></div>\r\n"
		"<div><label>To</label><textarea name=\"To\">%s</textarea></div>\r\n"
		"<div><label>At</label><textarea name=\"At\">%s</textarea></div>\r\n"
		"</div>\r\n"
		"<div class=\"hk-form-row\"><label>Apply Overrides to unsent Bulls</label><input name=\"OvUnsent\" %svalue=\"OvUnsent\" type=\"checkbox\"></div>\r\n"
		"</div>\r\n"
		"</div>\r\n"
		"</div>\r\n"
		"\r\n"
		"<div class=\"hk-buttons\"><input name=\"Save\" value=\"Save\" type=\"submit\" class='btn'><input name=\"Cancel\" value=\"Cancel\" type=\"submit\" class='btn'></div>\r\n"
		"</form>\r\n"
		"</div>\r\n"
		"</body></html>\r\n";

	return _strdup(Msg);
}

char * WPtxt()
{
	static const char Msg[] =
		"<!-- Version 3 3/9/2026 Refactored -->\r\n"
		"<!DOCTYPE html>\r\n"
		"<html lang=\"en\"><head>\r\n"
		"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
		"<meta charset=\"UTF-8\">\r\n"
		COMMON_BPQ_CSS_LINK
		"<title>Edit WP</title>\r\n"
		"<style>"
		COMMON_PAGE_BASE_CSS
		COMMON_ADMIN_LIST_TOGGLE_CSS_TEMPLATE(".wp-list-toggle")
		COMMON_ADMIN_LIST_BODY_CSS_TEMPLATE(".wp-list-body")
		".wp-container{max-width:980px;margin:0 auto;}"
		".wp-title{text-align:center;font-family:" COMMON_FONT_TITLE ";font-size:clamp(1.25rem,1.05rem + 0.9vw,1.75rem);font-weight:700;margin:12px 0 0;color:var(--text);}"
		".wp-layout{display:flex;gap:20px;flex-wrap:wrap;align-items:start;}"
		".wp-sidebar{flex:0 0 280px;min-width:0;display:flex;flex-direction:column;max-height:calc(100vh - 240px);}"
		".wp-list{background:var(--surface);padding:15px;border:1px solid var(--border);border-radius:8px;box-shadow:var(--shadow-card);overflow:hidden;flex:1 1 auto;display:flex;flex-direction:column;min-height:0;}"
		".wp-list a.active{background:var(--surface-soft);}"
		".wp-list-toggle{font-family:" COMMON_FONT_TITLE ";}"
		".wp-list table{width:100%%;border-collapse:collapse;}"
		".wp-list table tr:nth-child(even){background:var(--table-stripe);}"
		".wp-list td{border-bottom:1px solid var(--border-light);padding:0;}"
		".wp-list a{color:var(--text);text-decoration:none;display:block;padding:8px 10px;border-radius:0;font-family: " COMMON_FONT_MONO ";font-weight:600;text-transform:uppercase;}"
		".wp-list a:hover{background:var(--surface-soft);text-decoration:none;}"
		".wp-main{flex:1 1 500px;min-width:0;background:var(--surface);padding:20px;border:1px solid var(--border);border-radius:8px;box-shadow:var(--shadow-card);min-height:400px;}"
		".wp-main input[type=text],.wp-main input[type=password],.wp-main input:not([type]),.wp-main textarea{background:var(--surface-soft);color:var(--text);border:1px solid var(--border);border-radius:6px;}"
		".wp-main input[type=text]:focus-visible,.wp-main input[type=password]:focus-visible,.wp-main input:not([type]):focus-visible,.wp-main textarea:focus-visible{outline:3px solid var(--focus-ring);outline-offset:2px;}"
		"@media (max-width:768px){"
		".wp-layout{flex-direction:column;align-items:stretch;}"
		".wp-sidebar{max-height:none;}"
		COMMON_ADMIN_COLLAPSIBLE_LIST_MOBILE_CSS_TEMPLATE(".wp-list", ".wp-list-body", ".wp-list-toggle", ".wp-list.collapsed .wp-list-body")
		".wp-list-body{width:100%%;box-sizing:border-box;}"
		".wp-main{order:2;padding:15px;}"
		"}"
		"</style>\r\n"
		"\r\n"
		COMMON_BPQ_JS_SCRIPT
		"<script type=\"text/javascript\">\r\n"
		"var Details;\r\n"
		"var Sidebar;\r\n"
		"var CurrentWP=\"\";\r\n"
		"var WPListCollapsed=false;\r\n"
		"var Key=\"%s\";\r\n"
		"function initialize()\r\n"
		"{	\r\n"
		"	Details = document.getElementById('main'); \r\n"
		"	if (Details) { Details.innerHTML = 'waiting for data...'; GetData(); }\r\n"
		"}\r\n"
		"\r\n"
		"function save(form)\r\n"
		"{\r\n"
		"	var msg\r\n"
		"	msg = form.Name.value + \"|\" + form.Home1.value+ \"|\" + form.Home2.value+ \"|\" + form.QTH1.value+ \"|\" + form.QTH2.value+ \"|\" + form.ZIP1.value + \"|\" + form.ZIP2.value +\"|\"\r\n"
		"	var fn = \"WPSave?\" + Key;\r\n"
		"	post(fn, msg);\r\n"
		"}\r\n"
		"\r\n"
		"function del(form)\r\n"
		"{\r\n"
		"	var msg\r\n"
		"	msg = form.Name.value + \"|\" + form.Home1.value+ \"|\" + form.Home2.value+ \"|\" + form.QTH1.value+ \"|\" + form.QTH2.value+ \"|\" + form.ZIP1.value + \"|\" + form.ZIP2.value +\"|\"\r\n"
		"	var fn = \"WPSave?\" + Key;\r\n"
		"	xpost(fn, \"Delete\", \"\");\r\n"
		"}\r\n"
		"\r\n"
		"function post(url, data)\r\n"
		"{\r\n"
		"\tif (window.XMLHttpRequest){request=new XMLHttpRequest();}else{request=new ActiveXObject(\"Microsoft.XMLHTTP\");}\r\n"
		"\trequest.onreadystatechange = function()\r\n"
		"\t{if (request.readyState == 4){Details.innerHTML = request.responseText;}}\r\n"
		"\trequest.open(\"POST\", url, true);request.send(data);\r\n"
		"}\r\n"
		"function xpost(url, data, call)\r\n"
		"{\r\n"
		"\tif (window.XMLHttpRequest){request=new XMLHttpRequest();}else{request=new ActiveXObject(\"Microsoft.XMLHTTP\");}\r\n"
		"\trequest.onreadystatechange = function()\r\n"
		"\t{if (request.readyState == 4){\r\n"
		"\t\tvar text = request.responseText;\r\n"
		"\t\tvar lines = text.split(\"|\");\r\n"
		"\t\tvar selected = call || lines[0] || '';\r\n"
		"\t\tvar infoArea = document.getElementById(\"sidebar\");\r\n"
		"\t\tCurrentWP = selected;\r\n"
		"\t\tinfoArea.innerHTML = buildWPList(lines);\r\n"
		"\t\tapplyWPListState();\r\n"
		"\t\tif (selected)\r\n"
		"\t\t{\r\n"
		"\t\t\tGetDetails(selected, true);\r\n"
		"\t\t}\r\n"
		"\t\telse if (Details)\r\n"
		"\t\t{\r\n"
		"\t\t\tDetails.innerHTML = 'No White Pages records found.';\r\n"
		"\t\t}\r\n"
		"\t}}\r\n"
		"\trequest.open(\"POST\", url, true);request.send(data);\r\n"
		"}\r\n"
		"function isMobile(){return window.matchMedia('(max-width: 768px)').matches;}\r\n"
		"function applyWPListState(){var sidebar=document.getElementById('sidebar');if(!sidebar)return;if(isMobile()&&WPListCollapsed){sidebar.classList.add('collapsed');}else{sidebar.classList.remove('collapsed');}}\r\n"
		"function toggleWPList(){if(!isMobile())return;WPListCollapsed=!WPListCollapsed;applyWPListState();}\r\n"
		"function buildWPList(lines){var i=0;var strInfo='<div class=\"wp-list\"><button type=button class=\"wp-list-toggle\" onclick=\"toggleWPList()\">White Pages List</button><div class=\"wp-list-body\"><table>';while(i < lines.length - 1){var active=(lines[i]===CurrentWP)?' class=\"active\"':'';var clink='<a'+active+' href=\\'javascript:GetDetails(\\\"'+lines[i]+'\\\",false)\\'>'+lines[i]+'</a>';strInfo += '<tr><td>' + clink + '</td></tr>';i=i+1;}return strInfo + '</table></div></div>';}\r\n"
		"function GetDetails(call, autoSelect)\r\n"
		"{\r\n"
		"	CurrentWP = call;\r\n"
		"	if (!autoSelect && isMobile()) { WPListCollapsed = true; applyWPListState(); }\r\n"
		"	var fn = \"WPDetails?\" + Key;\r\n"
		"	post(fn, call);\r\n"
		"}\r\n"
		"function GetData()\r\n"
		"{\r\n"
		"\tif (window.XMLHttpRequest){request=new XMLHttpRequest();}else{request=new ActiveXObject(\"Microsoft.XMLHTTP\");}\r\n"
		" \r\n"
		"\trequest.onreadystatechange = function()\r\n"
		"\t{\r\n"
		"\t\tif (request.readyState == 4)\r\n"
		"\t\t{\r\n"
		"\t\t\tvar text = request.responseText;\r\n"
		"\t\t\tvar lines = text.split(\"|\");\r\n"
		"\t\t\t\r\n"
		"\t \t    var infoArea = document.getElementById(\"sidebar\"); \r\n"
		"\t\t    infoArea.innerHTML = buildWPList(lines);\r\n"
		"\t\t    applyWPListState();\r\n"
		"\t\t    if (lines[0]) GetDetails(lines[0], true); else Details.innerHTML = 'No White Pages records found.';\r\n"
		"\t\t}\r\n"
		"\t}\r\n"
		"\trequest.open(\"GET\",\"WPInfo.txt?%s\",true);\t\t\t\t\t\t\t   \r\n"
		"\trequest.send();\r\n"
		"}\r\n"
		"window.addEventListener('resize', function(){ if (!isMobile()) WPListCollapsed = false; applyWPListState(); });\r\n"
		" \r\n"
		"</script>\r\n"
		"</head><body onload=\"initialize()\">\r\n"
		"<div class=\"wp-container\">\r\n"
		"<h2>BPQ32 BBS %s</h2>\r\n"
		"<div class=menu-header><button id=menuToggle class=menu-toggle type=button onclick=\"toggleMenu(event)\">Menu</button></div>"
		"<div id=mailMenu class=menu>"
		"<a href=\"/Mail/Status?%s\">Status</a>"
		"<a href=\"/Mail/Conf?%s\">Configuration</a>"
		"<a href=\"/Mail/Users?%s\">Users</a>"
		"<a href=\"/Mail/Msgs?%s\">Messages</a>"
		"<a href=\"/Mail/FWD?%s\">Forwarding</a>"
		"<a href=\"/Mail/Wel?%s\">Welcome Msgs &amp; Prompts</a>"
		"<a href=\"/Mail/HK?%s\">Housekeeping</a>"
		"<a href=\"/Mail/WP?%s\">WP Update</a>"
		"<a href=/Webmail>WebMail</a>"
		"<a href=\"/\">Node Menu</a>"
		"</div>"
		"<div class=\"wp-title\">White Pages</div>\r\n"
		"<div class=\"wp-layout\">\r\n"
		"<div class=\"wp-sidebar\" id=\"sidebar\"></div>\r\n"
		"<div class=\"wp-main\" id=\"main\"></div>\r\n"
		"</div>\r\n"
		"</div>\r\n"
		"</body></html>\r\n";

	return _strdup(Msg);
}


char * ChatConfigtxt()
{
	static const char Msg[] =
		"<!-- Version 4 3/22/2026 Responsive refresh -->\r\n"
		"<!DOCTYPE html>\r\n"
		"<html lang=\"en\"><head>\r\n"
		"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
		"<meta charset=\"UTF-8\">\r\n"
		COMMON_BPQ_CSS_LINK
		"<style>"
		COMMON_PAGE_BASE_CSS
		"body{margin:0;padding:12px;background-image:url(/background.jpg);box-sizing:border-box;}"
		"h3{margin:0 0 10px;text-align:center;}"
		"#main{" COMMON_CARD_CHROME_CSS "overflow:auto;text-align:center;position:relative;min-height:650px;width:min(960px,100%%);margin:10px auto 0;padding:14px;box-sizing:border-box;}"
		"#main form{font-family: " COMMON_FONT_MONO ";text-align:left;}"
		"#main input[type=text],#main input[type=number],#main input:not([type]),#main textarea{border:1px solid var(--border);border-radius:6px;" COMMON_INPUT_BASE_CSS "font-family:" COMMON_FONT_MONO ";}"
		"#main input[type=text],#main input:not([type]){max-width:100%%;}"
		"#main textarea{width:100%%;resize:vertical;}"
		".chatcfg-title{text-align:center;font-family:" COMMON_FONT_TITLE ";font-size:clamp(1.25rem,1.05rem + 0.9vw,1.75rem);font-weight:700;margin:6px 0 0;}"
		".chatcfg-formrow{display:flex;align-items:center;gap:10px;margin:10px 0;flex-wrap:wrap;}"
		".chatcfg-formrow label{font-weight:600;}"
		".chatcfg-formrow .num{width:90px;}"
		".chatcfg-formrow .grow{flex:1 1 auto;}"
		".chatcfg-check{display:flex;align-items:center;gap:8px;margin:10px 0 14px;}"
		".chatcfg-info{width:100%%;max-width:100%%;margin:0 auto;text-align:left;line-height:1.4;border:1px solid var(--border-light);background:var(--surface-soft);border-radius:6px;padding:10px 12px;box-sizing:border-box;}"
		".chatcfg-block{margin:12px 0;}"
		".chatcfg-block label{display:block;font-weight:600;margin-bottom:6px;}"
		".chatcfg-inline{display:flex;align-items:center;gap:10px;flex-wrap:wrap;}"
		".chatcfg-actions{display:flex;flex-wrap:wrap;justify-content:center;gap:10px;margin-top:14px;}"
		"@media (max-width:768px){body{padding:8px;}#main{min-height:0;padding:10px;}.chatcfg-formrow{flex-direction:column;align-items:stretch;}.chatcfg-formrow .num{width:100%%;}#main input[type=text],#main input[type=number],#main input:not([type]),#main textarea,.btn{width:100%%;min-height:48px;}.chatcfg-inline{justify-content:flex-start;}.chatcfg-actions{justify-content:stretch;}}"
		"</style>"
		"<title>Chat Configuration</title>\r\n"
		COMMON_BPQ_JS_SCRIPT
		"<script type=\"text/javascript\">\r\n"
		"var Main;\r\n"
		"var Pos;\r\n"
		"var Poptext;\r\n"
		"\r\n"
		"function initialize()\r\n"
		"{\r\n"
		"Main = document.getElementById(\"main\");\r\n"
		"Pos = document.getElementById(\"pos\");\r\n"
		"Poptext = document.getElementById(\"poptext\");\r\n"
		"\r\n"
		"\r\n"
		"}\r\n"
		"function CheckLen()\r\n"
		"{\r\n"
		"var len = Pos.value.length + Poptext.value.length;\r\n"
		"if (len > 245)\r\n"
		"	{alert(\"Combinded length of Location and Popup Text must not exceed 245. Now \" + len);}\r\n"
		"}\r\n"
		"</script>\r\n"
		"</head>\r\n"
		"<body onload=\"initialize()\" onresize=\"initialize()\">\r\n"
		"<h2>BPQ32 Chat Node %s</h2>\r\n"
		"<div class=\"menu-header\"><button id=\"menuToggle\" class=\"menu-toggle\" type=\"button\" onclick=\"toggleMenu(event)\">Menu</button></div>\r\n"
		"<div id=\"chatMenu\" class=\"menu\">\r\n"
		"<a href=\"/Chat/ChatStatus?%s\">Status</a>\r\n"
		"<a href=\"/Chat/ChatConf?%s\">Configuration</a>\r\n"
		"<a href=\"/\">Node Menu</a>\r\n"
		"</div>\r\n"
		"<div class=\"chatcfg-title\">Chat Configuration</div>\r\n"
		"<div id=\"main\">\r\n"
		"<form border=\"1\" style=\"font-family: " COMMON_FONT_MONO ";\" method=\"post\"\r\n"
		"action=\"/Chat/ChatConfig?%s\">\r\n"
		"<h3>Chat Server Params</h3>\r\n"
		"<div class=\"chatcfg-formrow\"><label for=\"chatappl\">Chat APPL No</label><input id=\"chatappl\" class=\"num\" value=\"%d\" size=\"3\" name=\"ApplNum\" type=\"number\"></div>\r\n"
		"<div class=\"chatcfg-formrow\"><label for=\"chatstreams\">Streams</label><input id=\"chatstreams\" class=\"num\" value=\"%d\" size=\"3\" name=\"Streams\" type=\"number\"></div>\r\n"
		"<label class=\"chatcfg-check\"><input %sname=\"Events\" type=\"checkbox\"> Enable Event Reporting</label>\r\n"

		"<div class=\"chatcfg-info\">The Nodes to link to box defines which other Chat Nodes should be connected to, or from which "
		"connections may be accepted. The format is ALIAS:CALL, eg BPQCHT:G8BPQ-4. If the node is not directly "
		"connectable (ie is not in your NODES table) you can add a connect script. This consists of a series of commands "
		"separared by |, eg NOTCHT:G8BPQ-4|C 3 GM8BPQ-9|CHAT"

		"<br><br>The Callsign of the Chat Node is not defined here - it is obtained from the bpq32.cfg APPLICATION line corresponding to the Chat Appl Number.</div>\r\n"
		"<div class=\"chatcfg-block\"><label for=\"nodes\">Nodes to link to</label><textarea id=\"nodes\" cols=\"70\" rows=\"5\" name=\"nodes\">%s</textarea></div>\r\n"
		"<div class=\"chatcfg-formrow\"><label for=\"paclen\">Node to Node Link PACLEN</label><input id=\"paclen\" class=\"num\" value=\"%d\" size=\"3\" name=\"Paclen\" type=\"number\"></div>\r\n"
		"<div class=\"chatcfg-formrow\"><label for=\"pos\">Map Position</label><input class=\"grow\" onchange=\"CheckLen()\" maxlength=\"80\" value=\"%s\" size=\"20\" name=\"Posn\" id=\"pos\"></div>\r\n"
		"<div class=\"chatcfg-formrow\"><label>Popup Type</label><div class=\"chatcfg-inline\">Hover <input %s name=\"PopType\" value=\"Hover\" type=\"radio\"> Click <input %s name=\"PopType\" value=\"Click\" type=\"radio\"></div></div>\r\n"
		"<div class=\"chatcfg-block\"><label for=\"poptext\">Map Popup Text</label><input onchange=\"CheckLen()\" maxlength=\"250\" value=\"%s\" size=\"90\" name=\"MapText\" id=\"poptext\"></div>\r\n"
		"<div class=\"chatcfg-block\"><label for=\"welcome\">Welcome Message</label><textarea id=\"welcome\" cols=\"80\" rows=\"5\" name=\"welcome\">%s</textarea></div>\r\n"
		"\r\n"
		"<div class=\"chatcfg-actions\">\r\n"
		"<input name=\"Save\" value=\"Save\" type=\"submit\" class=\"btn\"> \r\n"
		"<input name=\"UpdateMap\" value=\"Update Map\" type=\"submit\" class=\"btn\"> \r\n"
		"<input name=\"Restart\" value=\"Restart Links\" type=\"submit\" class=\"btn\"> \r\n"
		"<input name=\"Cancel\" value=\"Cancel\"\r\n"
		"type=\"submit\" class=\"btn\"></div>\r\n"
		"</form>\r\n"
		"</div>\r\n";

	return _strdup(Msg);
}


char * ChatStatustxt()
{
	static const char Msg[] =
		"<!-- Version 2 3/9/2026 Refactored -->\r\n"
		"<!DOCTYPE html>\r\n"
		"<style>"
		COMMON_PAGE_BASE_CSS
		"@media (max-width:768px){}"
		"</style>"
		"<html lang=\"en\"><head>\r\n"
		"<meta charset=\"UTF-8\">\r\n"
		COMMON_BPQ_CSS_LINK
		"<style>"
		"#outer{width:720px;height:700px;position:absolute;border:0px solid;font-family: " COMMON_FONT_MONO ";}"
		"#streams{width:360px;position:absolute;height:300px;left:2px;" COMMON_PANEL_CHROME_CSS "overflow:auto}"
		"#users{position:absolute;top:307px;left:2px;width:710px;height:350px;" COMMON_PANEL_CHROME_CSS "overflow:auto;}"
		"#links{position:absolute;left:370px;width:341px;height:300px;" COMMON_PANEL_CHROME_CSS "overflow:auto;}"
		"</style>\r\n"
		"<title>%s's Chat Server</title>\r\n"
		"  \r\n"
		COMMON_BPQ_JS_SCRIPT
		"<script type=\"text/javascript\">\r\n"
		"\r\n"
		"var Outer;\r\n"
		"var Selected;\r\n"
		"var Inpval;\r\n"
		"var SelectedStream = 0;\r\n"
		"\r\n"
		"function initialize()\r\n"
		"{\r\n"
		" var w=window,d=document,e=d.documentElement,g=d.getElementsByTagName('body')[0];\r\n"
		" x=w.innerWidth||e.clientWidth||g.clientWidth;\r\n"
		" y=w.innerHeight||e.clientHeight||g.clientHeight;\r\n"
		" fromleft = (x / 2) - 360;\r\n"
		"\r\n"
		" if (fromleft < 0) {fromleft = 0;}\r\n"
		" Outer = document.getElementById(\"outer\");\r\n"
		" Outer.style.left = fromleft + \"px\";\r\n"
		" Inpval = document.getElementById(\"inpval\");\r\n"
		"}\r\n"
		" \r\n"
		"function SelectRow(newRow)\r\n"
		"{\r\n"
		" var cell=document.getElementById(\"cell_\" + newRow);\r\n"
		" var Last = Selected;\r\n"
		" Selected = cell;\r\n"
		" SelectedStream = newRow\r\n"
		" cell.style.background=\"var(--table-selected)\";\r\n"
		" if (Last)\r\n"
		"  {Last.style.background=\"var(--surface)\"};\r\n"
		" if (cell == Last)\r\n"
		" {\r\n"
		"  SelectedStream = 0;\r\n"
		" }\r\n"
		"  Inpval.value = SelectedStream;\r\n"
		"}\r\n"
		"\r\n"
		"function condRefresh()\r\n"
		"{\r\n"
		"	if (SelectedStream == 0)\r\n"
		"		{location.reload(true);}\r\n"
		"}\r\n"
		"\r\n"
		"window.setInterval(condRefresh, 10000);\r\n"
		"\r\n"
		"</script>\r\n"
		"</head><body onload=\"initialize()\" onresize=\"initialize()\">\r\n"
		"<h2 align=\"center\">BPQ32 Chat Server %s</h2>\r\n"
		"\r\n"
		"<div class=\"menu-header\"><button id=\"menuToggle\" class=\"menu-toggle\" type=\"button\" onclick=\"toggleMenu(event)\">Menu</button></div>\r\n"
		"<div id=\"chatMenu\" class=\"menu\">\r\n"
		"<a href=\"/Chat/ChatStatus?%s\">Status</a>\r\n"
		"<a href=\"/Chat/ChatConf?%s\">Configuration</a>\r\n"
		"<a href=\"/\">Node Menu</a>\r\n"
		"</div>\r\n"
		"\r\n"
		"<br>\r\n"
		"\r\n"
		"<div style=\"left: 160px;\" id=\"outer\">\r\n"
		"<div id=\"streams\">\r\n"
		"<form style=\"font-family: " COMMON_FONT_MONO "; text-align: center;\" method=\"post\" action=\"/Chat/ChatDisSession?%s\">\r\n"
		"  <table style=\"font-family: " COMMON_FONT_MONO "; background-color: var(--surface); text-align: left; margin-left: auto; margin-right: auto;\" tabindex=\"1\" border=\"1\" cellpadding=\"2\">\r\n"
		"    <tbody>\r\n"
		"      <tr>\r\n"
		"        <th style=\"width: 120px;\">User</th>\r\n"
		"        <th style=\"width: 75px;\">Callsign</th>\r\n"
		"        <th>Stream</th>\r\n"
		"        <th style=\"width: 80px;\">Topic</th>\r\n"
		"        <th>Queue</th>\r\n"
		"      </tr>\r\n"
		"%s\r\n"
		"    </tbody>\r\n"
		"  </table>\r\n"
		" <input type=\"hidden\" name=Stream value=99 id=inpval>\r\n"
		"<input align = center value=Disconnect type=submit class='btn'> \r\n"
		"<br>\r\n"
		"  </form>\r\n"
		"</div>\r\n"
		"<div id=\"users\">\r\n"
		"<table style=\"font-family: " COMMON_FONT_MONO "; background-color: var(--surface); text-align: left; margin-left: auto; margin-right: auto;\" tabindex=\"1\" border=\"1\" cellpadding=\"2\">\r\n"
		"  <tbody>\r\n"
		"    <tr>\r\n"
		"      <th style=\"width: 75px;\">Callsign</th>\r\n"
		"      <th style=\"width: 75px;\">Node</th>\r\n"
		"      <th style=\"width: 80px;\">Name</th>\r\n"
		"      <th style=\"width: 80px;\">Topic</th>\r\n"
		"      <th>Idle</th>\r\n"
		"      <th style=\"width: 320px;\">QTH</th>\r\n"
		"    </tr>\r\n"
		"%s\r\n"
		"  </tbody>\r\n"
		"</table>\r\n"
		"</div>\r\n"
		"<div id=\"links\">\r\n"
		"<table style=\"font-family: " COMMON_FONT_MONO "; background-color: var(--surface); text-align: left; tabindex=\"1\" border=\"1\" cellpadding=\"2\">\r\n"
		"  <tbody>\r\n"
		"    <tr>\r\n"
		"      <th style=\"width: 80px;\">Callsign</th>\r\n"
		"      <th style=\"width: 110px;\">State</th>\r\n"
		"      <th style=\"width: 75px;\">Nodes</th>\r\n"
		"      <th>Users</th>\r\n"
		"    </tr>\r\n"
		"%s\r\n"
		"  </tbody>\r\n"
		"</table>\r\n"
		"</div>\r\n"
		"</div>\r\n";

	return _strdup(Msg);
}
