# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------


TEMPLATE = app
TARGET = BPQConfigGen
QT += core gui widgets network
CONFIG += debug
HEADERS += ./BPQConfigGen.h
SOURCES += ./BPQConfigGen.cpp \
    ./main.cpp
FORMS += ./BPQConfigGen.ui
RESOURCES += BPQConfigGen.qrc

