	PAGE    56,132
;
.386
.LALL
.LFCOND


;	 OCTOBER 2006 SUPPORT UP TO 8 L4 APPLICATION CALL/ALIAS PAIRS

;	May 2008 Fix convtoax25 to handle null-terminated call strings (UNPROTO SSID Problem)

;	Oct 2008 Put pushad/popad round INITIALISEPORTS

;
;  SEGMENT definitions and order
;


;*	32 Bit code
_TEXT		SEGMENT DWORD USE32 PUBLIC 'CODE'
_TEXT		ENDS


;*	Contains 32 Bit data
_BPQDATA		SEGMENT DWORD PUBLIC 'DATA'
_BPQDATA		ENDS



	ASSUME CS:FLAT, DS:FLAT, ES:FLAT, SS:FLAT

OFFSET32 EQU <OFFSET FLAT:>

	INCLUDE STRUCS.INC


_BPQDATA	SEGMENT
;
;	POINTERS TO TABLES ARE AT START TO SIMPLIFY DIAGNOSTIC 
;	 DUMP ANALYSIS, AND NODES SAVE ROUTINES
;
	extern	_FREE_Q:DWORD
	EXTRN	_MaxHops:DWORD, _MAXRTT:DWORD,_SIGNONMSG:BYTE

	EXTRN	_MAXCIRCUITS:WORD		; NUMBER OF L4 CIRCUITS
	EXTRN	_PORTTABLE:DWORD,_NUMBEROFPORTS:DWORD

	EXTRN	_ENDDESTLIST:DWORD		; _NODE LIST+1
;
	EXTRN	_BUFFERPOOL:DWORD		; START OF BUFFER POOL

	EXTRN	_OBSINIT:DWORD		; INITIAL OBSOLESCENCE VALUE
	EXTRN	_OBSMIN:DWORD		; MINIMUM TO BROADCAST
	EXTRN	_L3INTERVAL:DWORD		; 'NODES' INTERVAL IN MINS
	EXTRN	_IDINTERVAL:DWORD		; 'ID' BROADCAST INTERVAL
	EXTRN	_BTINTERVAL:DWORD		; 'BT' BROADCAST INTERVAL
	EXTRN	_MINQUAL:DWORD		; MIN QUALITY FOR AUTOUPDATES
	EXTRN	_HIDENODES:DWORD		; N * COMMAND SWITCH
	EXTRN	_BBSQUAL:DWORD		; QUALITY OF _BBS RELATIVE TO _NODE
;
	EXTRN	_NUMBEROFBUFFERS:DWORD		; PACKET BUFFERS

	EXTRN	_PACLEN:DWORD		; MAX PACKET SIZE
;
	EXTRN	_T3:DWORD		; LINK VALIDATION TIMER (3 MINS) (+ a bit to reduce RR collisions)

	EXTRN	_L2KILLTIME:DWORD	; IDLE LINK TIMER (16 MINS)	

	EXTRN	_L3LIVES:DWORD		; MAX L3 HOPS
	EXTRN	_L4N2:DWORD		; LEVEL 4 RETRY COUNT
	EXTERN _L4T1:DWORD ; LEVEL 4 TIMEOUT
	EXTRN	_L4LIMIT:DWORD		; IDLE SESSION LIMIT - 15 MINS
	EXTRN	_L4DELAY:DWORD		; L4 DELAYED ACK TIMER
	EXTERN _L4DEFAULTWINDOW:BYTE	; DEFAULT WINDOW
	
	EXTRN	_BBS:DWORD		; INCLUDE _BBS SUPPORT
	EXTRN	_NODE:DWORD		; INCLUDE SWITCH SUPPORT
	EXTRN	_BPQHOSTVECTOR:BYTE,_AUTOSAVE:DWORD,_L4APPL:DWORD,_CFLAG:DWORD

	EXTRN	_NEXTFREEDATA:DWORD				; OFFSET OF NEXT FREE BYTE

	EXTRN	_MYCALL:BYTE,_MYALIASTEXT:BYTE,_MYALIAS:BYTE,_MYNODECALL:BYTE,_NETROMCALL:BYTE,_APPLCALLTABLE:BYTE
	EXTRN	_MYNETROMCALL:BYTE
	
	EXTRN	_DESTS:DWORD,_LINKS:DWORD,_NEIGHBOURS:DWORD,_MAXLINKS:DWORD,_MAXNEIGHBOURS:DWORD
	EXTRN	_NORMCALL:BYTE,_AX25CALL:BYTE,_UNPROTOCALL:BYTE,_TEMPFIELD:BYTE,_NORMLEN:DWORD
	EXTRN	_IDMSG:DWORD,_INFOMSG:DWORD,_INFOLEN:DWORD
	EXTRN	_CURRENTPORT:DWORD,_CURRENTPORTPTR:DWORD
	EXTRN	_REALTIMETICKS:DWORD,_L2TIMERFLAG:DWORD,_L3TIMERFLAG:DWORD,_L4TIMERFLAG:DWORD
	EXTRN	_CONFIGPTR:DWORD,_BGTIMER:DWORD
	
	EXTRN	_HEADERCHAR:BYTE

	EXTRN	_CTEXTMSG:DWORD,_CTEXTLEN:DWORD,_TRACE_Q:DWORD,_LINKEDFLAG:DWORD
	
	EXTRN	_FULL_CTEXT:DWORD


	EXTRN	_MINBUFFCOUNT:WORD,_NOBUFFCOUNT:WORD,_MAXDESTS:WORD
	EXTRN	_IDTIMER:WORD,_QCOUNT:WORD,_ROUTEQUAL:BYTE,_APPLS:BYTE
	EXTRN	_DESTHEADER:DWORD,_BTTIMER:WORD,_NUMBEROFNODES:DWORD
	EXTRN	_MAXBUFFS:WORD,_NEEDMH:BYTE,_CMDALIAS:BYTE,_ALIASPTR:DWORD
	EXTRN	_STATSTIME:DWORD,_CMDXLEN:DWORD
	EXTRN	_BPQMsg:DWORD, _L3TIMER:WORD
	EXTRN	_IPRequired:DWORD, _IDMSG_Q:DWORD
	EXTRN	_L4TABLE:DWORD
	


;

	EVEN
;

DECODEDNAME	DB	20 DUP (0)	; CALL IN ALIAS:CALL FORMAT

;PACTORSAVEQ	DD	0		; Work area for PACTOR busy test.

BUFFERRMSG	DB	'Corrupt buffer pool detected and dump taken',10,0
	
_BPQDATA	ENDS

_TEXT	SEGMENT

	EXTRN	_CloseSessionPartner:NEAR

	extrn	_Sleep@4:near
	extrn	_DumpSystem@0:near
	extrn	_OpenConfigFile:near	
	extrn	_ReadFile@20:near
	extrn	_GetLastError@0:near
	extrn	_SetFilePointer@16:near
	extrn	_CloseHandle@4:near
	extrn	_PostMessageA@16:near
;	extrn	_printf:near
	extrn	_time:near
	extrn	_WriteFile@20:near
	extrn	_InitializeExtDriver:near
	extrn	_WritetoConsole@4:near
	extern  _FreeConfig:near

	PUBLIC	SEND_DOS_MESSAGE
SEND_DOS_MESSAGE:
;
;	SEND MESSAGE IN EDX 
;


;WriteFile(STDOUT,"Initialising..\n",15,&n,NULL);

	push	edx

	call    _WritetoConsole@4
	
	RET
 	


	PUBLIC	_Q_ADD_INIT
_Q_ADD_INIT:

	PUBLIC	_Q_ADDI05
_Q_ADDI05:

	CMP	DWORD PTR [ESI],0		; END OF CHAIN
	JE SHORT _Q_ADDI10

	MOV	ESI,[ESI]			; NEXT IN CHAIN
	JMP	_Q_ADDI05

	PUBLIC	_Q_ADDI10
_Q_ADDI10:
	MOV	DWORD PTR [EDI],0		; CLEAR CHAIN ON NEW BUFFER
	MOV	[ESI],EDI			; CHAIN ON NEW BUFFER

	INC	_QCOUNT
	RET



;	CW LOOKUP TABLE - TWO BITS PER ELEMENT
;
;		00 = END
;		01 = DIT
;		11 = DASH
;
;
;	BASED ON DESIGN BY MIKE TUBBY, G8TIC, 1985
;

_CWTABLE		DW	1101011101B	; /	-..-.
		DW	1111111111B	; 0	-----
		DW	1111111101B	; 1	.----
		DW	1111110101B	; 2	..---
		DW	1111010101B	; 3	...--
		DW	1101010101B	; 4	....-
		DW	0101010101B	; 5	.....
		DW	0101010111B	; 6	-....
		DW	0101011111B	; 7	--...
		DW	0101111111B	; 8	---..
		DW	0111111111B	; 9	----.

		DW	7 DUP (0)	; ASCII 3A-40

		DW	0000001101B	; A	.-
		DW	0001010111B	; B	-...
		DW	0001110111B	; C	-.-.
		DW	0000010111B	; D	-..
		DW	0000000001B	; E	.
		DW	0001110101B	; F	..-.
		DW	0000011111B	; G	--.
		DW	0001010101B	; H	....
		DW	0000000101B	; I	..
		DW	0011111101B	; J	.---

		DW	0000110111B	; K	-.-
		DW	0001011101B	; L	.-..
		DW	0000001111B	; M	--
		DW	0000000111B	; N	-.
		DW	0000111111B	; O	---
		DW	0001111101B	; P	.--.
		DW	0011011111B	; Q	--.-
		DW	0000011101B	; R	.-.
		DW	0000010101B	; S	...
		DW	0000000011B	; T	-
		DW	0000110101B	; U	..-
		DW	0011010101B	; V	...-
		DW	0000111101B	; W	.--
		DW	0011010111B	; X	-..-
		DW	0011110111B	; Y	-.--
		DW	0001011111B	; Z	--..

_TEXT	ENDS

_TEXT	SEGMENT
;
;	LOCKED CODE
;
	PUBLIC	Q_REM,_Q_ADD,RELBUFF,CONVFROMAX25,CONVTOAX25
	PUBLIC	GETPORTTABLEENTRY,GETBUFF
	PUBLIC	GETPORTQUALITY

	PUBLIC _RELBUFF
	
_RELBUFF	LABEL NEAR

RELBUFF:
;
;	see if buffer is already on free q
;
;	MOV	ESI,OFFSET32 _FREE_Q
;relaa:
;	cmp	esi,edi
;	je	relxx
	
;	mov	esi,[esi]
;	cmp	esi,0
;	je	relok					; end of chain
	
;	jmp relaa
	
;	cmp		EDI,0
;	jne		relok

;relxx:

;	CALL	CBBAD

;relok:

	
	MOV	ESI,OFFSET32 _FREE_Q
	CALL	_Q_ADDF			; RETURN BUFFER TO FREE QUEUE

	RET

	PUBLIC	GETPORTQUALITY
GETPORTQUALITY:

	PUSH	EBX

	CALL	GETPORTTABLEENTRY
	MOV	AL,PORTQUALITY[EBX]

	POP	EBX
	RET
			
	PUBLIC	GETPORTTABLEENTRY
GETPORTTABLEENTRY:

	PUSH	ECX
	MOV	EBX,_PORTTABLE
	MOV	ECX,_NUMBEROFPORTS
	JCXZ	GETNOPORTS

	PUBLIC	GETPORT10
GETPORT10:

	CMP	AL,PORTNUMBER[EBX]
	JE SHORT GETPORT20

	MOV	EBX,PORTPOINTER[EBX]
	LOOP	GETPORT10

	PUBLIC	GETNOPORTS
GETNOPORTS:

	MOV	EBX,_PORTTABLE		; TO FIRST IF NOT DEFINED

	PUBLIC	GETPORT20
GETPORT20:
	POP	ECX
	RET

	PUBLIC	CONVTOAX25
CONVTOAX25:
;
;	CONVERT CALLSIGN IN [ESI] TO AX25 FORMAT IN _AX25CALL
;	RETURN NZ IF CALLSIGN INVALID
;
	MOV	EDI,OFFSET32 _AX25CALL
	MOV	ECX,6			; MAX ALPHANUMERICS
	MOV	AL,40H
	REP STOSB			; CLEAR IN CASE SHORT CALL
	MOV	AL,01100000B		; DEFAULT SSID
	STOSB
	MOV	EDI,OFFSET32 _AX25CALL
	MOV	CL,7
	PUBLIC	CONVAX00
CONVAX00:
	LODSB
	CMP	AL,'-'
	JE SHORT CONVAX20		; SSID FOLLOWS
	CMP	AL,' '
	JBE SHORT CONVAX40		; END OF NAME
;
	CMP	AL,'#'
	JNE SHORT NOTHASH

	CMP	CL,7
	JE SHORT CONVAX10		; OK AS FIRST CHAR
	PUBLIC	NOTHASH
NOTHASH:
	CMP	AL,'/'			; ALLOW / AND DIGITS (FOR W0RLI!)
	JB SHORT CONVAX49		; INVALID
	CMP	AL,'9'
	JBE SHORT CONVAX10		; OK

	CMP	AL,'A'
	JB SHORT CONVAX49		; INVALID
	CMP	AL,'Z'
	JBE SHORT CONVAX10		; OK


	CMP	AL,'a'
	JB SHORT CONVAX10		; OK
	CMP	AL,'z'
	JA SHORT CONVAX49		; INVALID

	AND	AL,NOT 20H		; CONVERT TO UPPER CASE
	PUBLIC	CONVAX10
CONVAX10:
	SAL	AL,1			; SHIFT UP
	STOSB
	LOOP	CONVAX00
;
;	HAVE PROCESSED 7 CHARS - NAME IS INVALID
;
	JMP SHORT CONVAX49

	PUBLIC	CONVAX20
CONVAX20:
	LODSB				; FIRST CHAR IF SSID
	CMP	AL,'0'
	JB SHORT CONVAX49		; INVALID
	CMP	AL,'9'
	JA SHORT CONVAX49		; OK
;
	MOV	AH,AL			; SAVE
	LODSB
	CMP	AL,' '
	JBE SHORT CONVAX30		; END OF SSID
	CMP	AL,','
	JE SHORT CONVAX30		; END OF SSID

	INC	ESI			; OTHER CODE EXPECTS ESI TO POINT TO NEXT FIELD
	CMP	AL,'0'
	JB SHORT CONVAX49		; INVALID
	CMP	AL,'5'			; LIMIT 10 - 15
	JA SHORT CONVAX49		; OK
;
	SUB	AL,30H
	CMP	AH,'1'
	JNE SHORT CONVAX49		; IF 2 DIGITS, FIRST MUST BE 1

	ADD	AL,10
	MOV	AH,AL
	PUBLIC	CONVAX30
CONVAX30:
	SAL	AH,1			; UP 1 BIT
	OR	AH,01100000B		; DEFAULT RR BITS
	MOV	_AX25CALL+6,AH

	PUBLIC	CONVAX40
CONVAX40:
;
;	NO SSID SUPPLIED
;
	XOR	AL,AL			; SET ZERO
	RET

	PUBLIC	CONVAX49
CONVAX49:
	OR	AL,1			; SET NZ
	RET



	PUBLIC	CONVFROMAX25
CONVFROMAX25:
;
;	CONVERT AX25 FORMAT CALL IN [ESI] TO NORMAL FORMAT IN _NORMCALL
;	   RETURNS LENGTH IN CX AND NZ IF LAST ADDRESS BIT IS SET
;
	PUSH	ESI			; SAVE
	MOV	EDI,OFFSET32 _NORMCALL
	MOV	ECX,10			; MAX ALPHANUMERICS
	MOV	AL,20H
	REP STOSB			; CLEAR IN CASE SHORT CALL
	MOV	EDI,OFFSET32 _NORMCALL
	MOV	CL,6
	PUBLIC	CONVAX50
CONVAX50:
	LODSB
	CMP	AL,40H
	JE SHORT CONVAX60		; END IF CALL - DO SSID

	SHR	AL,1
	STOSB
	LOOP	CONVAX50
	PUBLIC	CONVAX60
CONVAX60:
	POP	ESI
	ADD	ESI,6			; TO SSID
	LODSB
	MOV	AH,AL			; SAVE FOR LAST BIT TEST
	SHR	AL,1
	AND	AL,0FH
	JZ SHORT CONVAX90		; NO SSID - FINISHED
;
	MOV	BYTE PTR [EDI],'-'
	INC	EDI
	CMP	AL,10
	JB SHORT CONVAX70
	SUB	AL,10
	MOV	BYTE PTR [EDI],'1'
	INC	EDI
	PUBLIC	CONVAX70
CONVAX70:
	ADD	AL,30H			; CONVERT TO DIGIT
	STOSB
	PUBLIC	CONVAX90
CONVAX90:
	MOV	ECX,EDI
	SUB	ECX,OFFSET32 _NORMCALL
	MOV	_NORMLEN,ECX		; SIGNIFICANT LENGTH

	TEST	AH,1			; LAST BIT SET?
	RET

	PUBLIC	Q_REM
Q_REM:

;	CALL	CHECKBUFFERS

	MOV	EDI,[ESI]			; GET ADDR OF FIRST BUFFER
	CMP	EDI,0
	JE SHORT Q_RET			; EMPTY

;	CALL	CHECKBUFFER_EDI	; MAKE SURE OK

	MOV	EAX,[EDI]			; CHAIN FROM BUFFER
	MOV	[ESI],EAX			; STORE IN HEADER

;	POP	[EDI]			; CALLERS ADDR 
;	PUSH	[EDI]
	PUBLIC	Q_RET
Q_RET:
	RET

;               
	PUBLIC	_Q_ADD
_Q_ADD:

	PUSH	EAX
	MOV		EAX,0

;	CALL	CHECKBUFFERS

;	CALL	CHECKBUFFER_EDI	; MAKE SURE EDI IS IN POOL
	
	PUBLIC	_Q_ADD05
_Q_ADD05:

	CMP	DWORD PTR [ESI],0		; END OF CHAIN
	JE SHORT _Q_ADD10

	CMP	ESI,[ESI]
	JNE SHORT _Q_ADD07		; OK
;
;	BUFFER IS CHAINED TO ITSELF !!
;
	CALL	CBBAD			; FORCE DUMP

	PUBLIC	_Q_ADD07
_Q_ADD07:

	MOV	ESI,[ESI]			; NEXT IN CHAIN

	CMP	ESI,EDI
	JNE SHORT _Q_ADD08		; OK
;
;	ADDRESS IS ALREADY ON QUEUE!!
;
	CALL	CBBAD			; FORCE DUMP

	PUBLIC	_Q_ADD08
_Q_ADD08:

;	CALL	CHECKBUFFER		; MAKE SURE ADDR IS OK
	
	INC	AX
	JNZ	_Q_ADD05
;
;	LOOP!!

	CALL	CBBAD			; FORCE DUMP

	PUBLIC	_Q_ADD10
_Q_ADD10:

	CMP	ESI,EDI
	JNE SHORT _Q_ADD12		; OK
;
;	WE ARE ABOUT TO CHAIN A BUFFER TO ITSELF!!
;
	CALL	CBBAD			; FORCE DUMP

	PUBLIC	_Q_ADD12
_Q_ADD12:

	MOV	DWORD PTR [EDI],0	; CLEAR CHAIN ON NEW BUFFER
	MOV	[ESI],EDI			; CHAIN ON NEW BUFFER

	POP	EAX
	
	RET

;
;	ADD TO FRONT OF QUEUE - MUST ONLY BE USED FOR FREE QUEUE
;
	PUBLIC	_Q_ADDF
_Q_ADDF:

	INC	_QCOUNT

;	CALL	CHECKBUFFER_EDI	; MAKE SURE EDI IS IN POOL

	MOV	EAX,[ESI]			; OLD FIRST IN CHAIN
	MOV	[EDI],EAX
	MOV	[ESI],EDI			; PUT NEW ON FRONT
;
	RET
	
	PUBLIC _GETBUFF
	
_GETBUFF	LABEL NEAR

	PUBLIC	GETBUFF
GETBUFF:

	MOV	ESI,OFFSET32 _FREE_Q
	CALL	Q_REM

	JZ SHORT NOBUFFS

	DEC	_QCOUNT

	MOV	AX,_QCOUNT
	CMP	AX,_MINBUFFCOUNT
	JA SHORT GETBUFFRET
	MOV	_MINBUFFCOUNT,AX
	PUBLIC	GETBUFFRET
GETBUFFRET:
	OR	AL,1			; SET NZ
;
;	FLAG BUFFER WITH ADDR OF CALLING ROUTINE (TRYING TO TRACK DOWN LOST BUFFERS!)
;
;	POP	[EDI]
;	PUSH	[EDI]
 	RET

	PUBLIC	NOBUFFS
NOBUFFS:

	INC	_NOBUFFCOUNT
	XOR	AL,AL
	RET
;


	
	PUBLIC	CBBAD
CBBAD:

	PUSHAD

	MOV	EDX,OFFSET32 BUFFERRMSG
	CALL	SEND_DOS_MESSAGE
   
	CALL	_DumpSystem@0

	push	10000
	call	_Sleep@4
	
	POPAD
	
	PUSH	0
	RET

	extern _BPQTRACE:NEAR
	
	PUBLIC	TRACEFRAME
TRACEFRAME:

	pushad
	PUSH	EDI
	CALL	_BPQTRACE
	POP EDI
	popad
	RET

		
	PUBLIC	DECODENODENAME, DECODEDNAME
DECODENODENAME:
;
;	ESI = TABLE ENTRY WITH AX25 CALL AND ALIAS
;
;	RETURNS ESI = 20 BYTE DECODED NAME IN FORM ALIAS:CALL
;		ECX = LENGTH OF STRING
;
	PUSH	EDI

	MOV	EDI,OFFSET32 DECODEDNAME
	MOV	ECX,10
	MOV	AX,'  '
	REP STOSW			; CLEAR IT

	CALL	CONVFROMAX25

	PUSH	ECX			; SAVE CALL LENGTH
	MOV	EDI,OFFSET32 DECODEDNAME

	cmp	BYTE PTR [ESI],20H	; Does it start with a null or a space ?
	jbe SHORT NO_MNEMONIC

	MOV	ECX,6			; MAX LENGTH

	PUBLIC	DECODEN10
DECODEN10:
	LODSB
	CMP	AL,' '
	JE SHORT DECODEN20
	STOSB

	LOOP	DECODEN10

	PUBLIC	DECODEN20
DECODEN20:

	MOV	AL,':'
	STOSB

	PUBLIC	NO_MNEMONIC
NO_MNEMONIC:

	POP	ECX
	MOV	ESI,OFFSET32 _NORMCALL
	REP MOVSB

	MOV	ECX,EDI

	POP	EDI

	MOV	ESI,OFFSET32 DECODEDNAME
	SUB	ECX,ESI
	RET


	
	extern _MYCALLWITHALIAS:BYTE

	PUBLIC	_SETUPNODEHEADER
_SETUPNODEHEADER:

	MOV	ESI,OFFSET32 _MYCALLWITHALIAS
	CALL	DECODENODENAME
;
	REP MOVSB

	MOV	AL,_HEADERCHAR
	STOSB
	MOV	AL,20H
	STOSB

	RET

	IF	BLACKBITS

	PUBLIC	BLACKLIST

BLACKLIST	DB	71 DUP (0)	; 10 ENTRIES, 7 BYTES EACH
BLACKEND	DD	BLACKLIST	; KEEP JUST AFTER LIST

	ENDIF



_TEXT	ENDS

END
